// Auto-generated cover-art manifest. Only confirmed local files are included.
'use strict';

const COVER_ART = Object.freeze({
    "1943": "images/nes_box_art/1943.webp",
    "Star Force FC": "images/nes_box_art/star-force.webp",
    "Akumajou Densetsu": "images/nes_box_art/castlevania-iii.webp",
    "Gradius II": "images/nes_box_art/gradius-ii.webp",
    "Parodius Da": "images/nes_box_art/parodius.webp",
    "Rampart": "images/nes_box_art/rampart.webp",
    "Twinbee": "images/nes_box_art/twinbee.webp",
    "Rolling Thunder": "images/nes_box_art/rolling-thunder.webp",
    "Castlequest": "images/nes_box_art/castlequest.webp",
    "Pro Wrestling": "images/nes_box_art/pro-wrestling.webp",
    "A Boy and His Blob": "images/nes_box_art/a-boy-and-his-blob.webp",
    "Double Dragon 2": "images/nes_box_art/double-dragon-ii.webp",
    "Double Dragon 3": "images/nes_box_art/double-dragon-iii.webp",
    "Ferrari Grand Prix Challenge": "images/nes_box_art/ferrari-grand-prix-challenge.webp",
    "Rambo": "images/nes_box_art/rambo.webp",
    "Tiger Heli": "images/nes_box_art/tiger-heli.webp",
    "Wizards and Warriors 1": "images/nes_box_art/wizards-and-warriors.webp",
    "Wizards and Warriors 2": "images/nes_box_art/wizards-and-warriors-ii-ironsword.webp",
    "Wizards and Warriors 3": "images/nes_box_art/wizards-and-warriors-iii-kuros-visions-of-power.webp",
    "WWF WrestleMania": "images/nes_box_art/wwf-wrestlemania.webp",
    "WWF Wrestling Challenge": "images/nes_box_art/wwf-wrestlemania-challenge.webp",
    "Die Hard": "images/nes_box_art/die-hard.webp",
    "Predator": "images/nes_box_art/predator.webp",
    "Vice Project Doom": "images/nes_box_art/vice-project-doom.webp",
    "Treasure Master": "images/nes_box_art/treasure-master.webp",
    "Gun Nac": "images/nes_box_art/gun-nac.webp",
    "Wizardry 1": "images/nes_box_art/wizardry-proving-grounds-of-the-mad-overlord.webp",
    "Wizardry 2": "images/nes_box_art/wizardry-knight-of-diamonds.webp",
    "Rockin Kats": "images/nes_box_art/rockin-kats.webp",
    "Wacky Races": "images/nes_box_art/wacky-races.webp",
    "Dr Jekyll and Mr Hyde": "images/nes_box_art/dr-jekyll-and-mr-hyde.webp",
    "MUSCLE": "images/nes_box_art/m-u-s-c-l-e.webp",
    "Toxic Crusaders": "images/nes_box_art/toxic-crusaders.webp",
    "Guardian Legend": "images/nes_box_art/guardian-legend-the.webp",
    "Legacy of the Wizard": "images/nes_box_art/legacy-of-the-wizard.webp",
    "Raid on Bungeling Bay": "images/nes_box_art/raid-on-bungeling-bay.webp",
    "Spelunker": "images/nes_box_art/spelunker.webp",
    "Adventures in the Magic Kingdom": "images/nes_box_art/adventures-in-the-magic-kingdom.webp",
    "Bionic Commando": "images/nes_box_art/bionic-commando.webp",
    "Chip n Dale Rescue Rangers 2": "images/nes_box_art/chip-n-dale-rescue-rangers-2.webp",
    "Chip n Dale Rescue Rangers": "images/nes_box_art/chip-n-dale-rescue-rangers.webp",
    "Code Name Viper": "images/nes_box_art/codename-viper.webp",
    "Commando": "images/nes_box_art/commando.webp",
    "Darkwing Duck": "images/nes_box_art/darkwing-duck.webp",
    "Destiny of an Emperor": "images/nes_box_art/destiny-of-an-emperor.webp",
    "Duck Tales": "images/nes_box_art/ducktales.webp",
    "Gargoyles Quest 2": "images/nes_box_art/gargoyle-s-quest-ii.webp",
    "Ghosts and Goblins": "images/nes_box_art/ghosts-n-goblins.webp",
    "Gun Smoke": "images/nes_box_art/gun-smoke.webp",
    "Legendary Wings": "images/nes_box_art/legendary-wings.webp",
    "Little Mermaid": "images/nes_box_art/little-mermaid-the.webp",
    "Little Nemo the Dream Master": "images/nes_box_art/little-nemo-dream-master.webp",
    "Mega Man 2": "images/nes_box_art/mega-man-2.webp",
    "Mega Man 3": "images/nes_box_art/mega-man-3.webp",
    "Mega Man 4": "images/nes_box_art/mega-man-4.webp",
    "Mega Man 5": "images/nes_box_art/mega-man-5.webp",
    "Mega Man 6": "images/nes_box_art/mega-man-6.webp",
    "Mega Man": "images/nes_box_art/mega-man.webp",
    "Mighty Final Fight": "images/nes_box_art/mighty-final-fight.webp",
    "Section Z": "images/nes_box_art/section-z.webp",
    "Street Fighter 2020": "images/nes_box_art/street-fighter-2010.webp",
    "Strider": "images/nes_box_art/strider.webp",
    "Trojan": "images/nes_box_art/trojan.webp",
    "Willow": "images/nes_box_art/willow.webp",
    "Burgertime": "images/nes_box_art/burgertime.webp",
    "Captain America": "images/nes_box_art/captain-america-and-the-avengers.webp",
    "Tag Team Wrestling": "images/nes_box_art/tag-team-wrestling.webp",
    "Werewolf The Last Warrior": "images/nes_box_art/werewolf.webp",
    "Immortal": "images/nes_box_art/immortal-the.webp",
    "Skate Or Die 2": "images/nes_box_art/skate-or-die-2.webp",
    "Dragon Warrior 2": "images/nes_box_art/dragon-warrior-ii.webp",
    "Dragon Warrior 3": "images/nes_box_art/dragon-warrior-iii.webp",
    "Dragon Warrior 4": "images/nes_box_art/dragon-warrior-iv.webp",
    "Hydlide": "images/nes_box_art/hydlide.webp",
    "Magmax": "images/nes_box_art/magmax.webp",
    "Terra Cresta": "images/nes_box_art/terra-cresta.webp",
    "Ultima Exodus": "images/nes_box_art/ultima-exodus.webp",
    "Zanac": "images/nes_box_art/zanac.webp",
    "Nigel Mansells World Challenge": "images/nes_box_art/nigel-mansell-s-world-championship-racing.webp",
    "Adventures of Lolo 2": "images/nes_box_art/adventures-of-lolo-2.webp",
    "Adventures of Lolo 3": "images/nes_box_art/adventures-of-lolo-3.webp",
    "Adventures of Lolo": "images/nes_box_art/adventures-of-lolo.webp",
    "Air Fortress": "images/nes_box_art/air-fortress.webp",
    "Kabuki Quantum Fighter": "images/nes_box_art/kabuki-quantum-fighter.webp",
    "Barbie": "images/nes_box_art/barbie.webp",
    "Tom and Jerry": "images/nes_box_art/tom-and-jerry.webp",
    "Adventure Island": "images/nes_box_art/adventure-island.webp",
    "Adventures of Dino-Riki": "images/nes_box_art/adventures-of-dino-riki.webp",
    "Bomberman 2": "images/nes_box_art/bomberman-ii.webp",
    "Bomberman": "images/nes_box_art/bomberman.webp",
    "Bonks Adventure": "images/nes_box_art/bonk-s-adventure.webp",
    "Milons Secret Castle": "images/nes_box_art/milon-s-secret-castle.webp",
    "Princess Tomato Salad Kingdom": "images/nes_box_art/princess-tomato-in-the-salad-kingdom.webp",
    "Robowarrior": "images/nes_box_art/robowarrior.webp",
    "Star Force NES": "images/nes_box_art/star-force.webp",
    "Starship Hector": "images/nes_box_art/starship-hector.webp",
    "Xexyz": "images/nes_box_art/xexyz.webp",
    "Bram Stokers Dracula": "images/nes_box_art/bram-stoker-s-dracula.webp",
    "Dragons Lair": "images/nes_box_art/dragon-s-lair.webp",
    "Solstice": "images/nes_box_art/solstice.webp",
    "Tombs and Treasures": "images/nes_box_art/tombs-and-treasure.webp",
    "City Connection": "images/nes_box_art/city-connection.webp",
    "Goal Two": "images/nes_box_art/goal-two.webp",
    "Maniac Mansion": "images/nes_box_art/maniac-mansion.webp",
    "Shatterhand": "images/nes_box_art/shatterhand.webp",
    "Totally Rad": "images/nes_box_art/totally-rad.webp",
    "Deja Vu": "images/nes_box_art/deja-vu.webp",
    "Rescue the Embassy Mission": "images/nes_box_art/rescue-the-embassy-mission.webp",
    "Shadowgate": "images/nes_box_art/shadowgate.webp",
    "Uncharted Waters": "images/nes_box_art/uncharted-waters.webp",
    "Adventures of Bayou Billy": "images/nes_box_art/adventures-of-bayou-billy-the.webp",
    "Batman Returns": "images/nes_box_art/batman-returns.webp",
    "Bucky o Hare": "images/nes_box_art/bucky-o-hare.webp",
    "Castlevania 2": "images/nes_box_art/castlevania-ii.webp",
    "Castlevania 3": "images/nes_box_art/castlevania-iii.webp",
    "Castlevania": "images/nes_box_art/castlevania.webp",
    "Contra": "images/nes_box_art/contra.webp",
    "Goonies 2": "images/nes_box_art/goonies-ii-the.webp",
    "Gradius": "images/nes_box_art/gradius.webp",
    "Gyruss": "images/nes_box_art/gyruss.webp",
    "Jackal": "images/nes_box_art/jackal.webp",
    "Life Force": "images/nes_box_art/life-force.webp",
    "Lone Ranger": "images/nes_box_art/lone-ranger-the.webp",
    "Metal Gear": "images/nes_box_art/metal-gear.webp",
    "Mission Impossible": "images/nes_box_art/mission-impossible.webp",
    "Monster In My Pocket": "images/nes_box_art/monster-in-my-pocket.webp",
    "Parodius": "images/nes_box_art/parodius.webp",
    "Rush n Attack": "images/nes_box_art/rush-n-attack.webp",
    "Snakes Revenge": "images/nes_box_art/snake-s-revenge.webp",
    "Stinger": "images/nes_box_art/stinger.webp",
    "Super C": "images/nes_box_art/super-c.webp",
    "Tiny Toon Adventures 2": "images/nes_box_art/tiny-toon-adventures-2.webp",
    "Tiny Toon Adventures": "images/nes_box_art/tiny-toon-adventures.webp",
    "T M N T 1": "images/nes_box_art/teenage-mutant-ninja-turtles.webp",
    "T M N T 2": "images/nes_box_art/teenage-mutant-ninja-turtles-ii.webp",
    "T M N T 3": "images/nes_box_art/teenage-mutant-ninja-turtles-iii.webp",
    "Top Gun": "images/nes_box_art/top-gun.webp",
    "Top Gun The Second Mission": "images/nes_box_art/top-gun-the-second-mission.webp",
    "Track and Field 2": "images/nes_box_art/track-and-field-ii.webp",
    "Zen Intergalactic Ninja": "images/nes_box_art/zen-intergalactic-ninja.webp",
    "Alien 3": "images/nes_box_art/alien-3.webp",
    "Friday the 13th": "images/nes_box_art/friday-the-13th.webp",
    "Gotcha The Sport": "images/nes_box_art/gotcha-the-sport.webp",
    "Incredible Crash Dummies": "images/nes_box_art/incredible-crash-dummies-the.webp",
    "Karate Kid": "images/nes_box_art/karate-kid-the.webp",
    "NFL Football": "images/nes_box_art/nfl.webp",
    "Nightmare on Elm Street": "images/nes_box_art/a-nightmare-on-elm-street.webp",
    "Pictionary": "images/nes_box_art/pictionary.webp",
    "Spiderman": "images/nes_box_art/spider-man-return-of-the-sinister-six.webp",
    "Terminator 2": "images/nes_box_art/terminator-2-judgment-day.webp",
    "Wolverine": "images/nes_box_art/wolverine.webp",
    "Zombie Nation": "images/nes_box_art/zombie-nation.webp",
    "Abadox": "images/nes_box_art/abadox.webp",
    "Alfred Chicken": "images/nes_box_art/alfred-chicken.webp",
    "SCAT": "images/nes_box_art/s-c-a-t.webp",
    "Shadow of the Ninja": "images/nes_box_art/shadow-of-the-ninja.webp",
    "Balloon Fight": "images/nes_box_art/balloon-fight.webp",
    "Clu Clu Land": "images/nes_box_art/clu-clu-land.webp",
    "Cobra Triangle": "images/nes_box_art/cobra-triangle.webp",
    "Donkey Kong 3": "images/nes_box_art/donkey-kong-3.webp",
    "Donkey Kong Jr": "images/nes_box_art/donkey-kong-jr.webp",
    "Donkey Kong": "images/nes_box_art/donkey-kong.webp",
    "Dragon Warrior": "images/nes_box_art/dragon-warrior.webp",
    "Dr Mario": "images/nes_box_art/dr-mario.webp",
    "Earthbound": "images/nes_box_art/earthbound.webp",
    "Excitebike": "images/nes_box_art/excitebike.webp",
    "Faxanadu": "images/nes_box_art/faxanadu.webp",
    "Final Fantasy": "images/nes_box_art/final-fantasy.webp",
    "Gumshoe": "images/nes_box_art/gumshoe.webp",
    "Gyromite": "images/nes_box_art/gyromite.webp",
    "Kid Icarus": "images/nes_box_art/kid-icarus.webp",
    "Kirbys Adventure": "images/nes_box_art/kirby-s-adventure.webp",
    "Kung Fu": "images/nes_box_art/kung-fu.webp",
    "Legend of Zelda": "images/nes_box_art/legend-of-zelda-the.webp",
    "Mach Rider": "images/nes_box_art/mach-rider.webp",
    "Mario Brothers": "images/nes_box_art/mario-bros.webp",
    "Metroid": "images/nes_box_art/metroid.webp",
    "Nintendo World Cup": "images/nes_box_art/nintendo-world-cup.webp",
    "Popeye": "images/nes_box_art/popeye.webp",
    "Rad Racer": "images/nes_box_art/rad-racer.webp",
    "Snake Rattle and Roll": "images/nes_box_art/snake-rattle-n-roll.webp",
    "Soccer": "images/nes_box_art/soccer.webp",
    "Stack up": "images/nes_box_art/stack-up.webp",
    "Super Mario Bros 2": "images/nes_box_art/super-mario-bros-2.webp",
    "Super Mario Bros 3": "images/nes_box_art/super-mario-bros-3.webp",
    "Super Mario Bros": "images/nes_box_art/super-mario-bros.webp",
    "Super Spike V Ball": "images/nes_box_art/super-spike-v-ball.webp",
    "Urban Champion": "images/nes_box_art/urban-champion.webp",
    "Wrecking Crew": "images/nes_box_art/wrecking-crew.webp",
    "Zelda 2 Adventure of Link": "images/nes_box_art/zelda-ii-the-adventure-of-link.webp",
    "Isolated Warrior": "images/nes_box_art/isolated-warrior.webp",
    "Darkman": "images/nes_box_art/darkman.webp",
    "Hook": "images/nes_box_art/hook.webp",
    "Hudson Hawk": "images/nes_box_art/hudson-hawk.webp",
    "Jurassic Park": "images/nes_box_art/jurassic-park.webp",
    "Robocop 2": "images/nes_box_art/robocop-2.webp",
    "Robocop 3": "images/nes_box_art/robocop-3.webp",
    "Cowboy Kid": "images/nes_box_art/cowboy-kid.webp",
    "World Champ": "images/nes_box_art/world-champ.webp",
    "Crystalis": "images/nes_box_art/crystalis.webp",
    "Guerilla War": "images/nes_box_art/guerrilla-war.webp",
    "P O W": "images/nes_box_art/p-o-w.webp",
    "Dragon Fighter": "images/nes_box_art/dragon-fighter.webp",
    "Kings Knight": "images/nes_box_art/king-s-knight.webp",
    "Batman": "images/nes_box_art/batman-the-video-game.webp",
    "Batman Return of The Joker": "images/nes_box_art/batman-return-of-the-joker.webp",
    "Blaster Master": "images/nes_box_art/blaster-master.webp",
    "Festers Quest": "images/nes_box_art/fester-s-quest.webp",
    "Gremlins 2": "images/nes_box_art/gremlins-2.webp",
    "Journey to Silius": "images/nes_box_art/journey-to-silius.webp",
    "Lemmings": "images/nes_box_art/lemmings.webp",
    "Platoon": "images/nes_box_art/platoon.webp",
    "Spy Hunter": "images/nes_box_art/spy-hunter.webp",
    "Super Spy Hunter": "images/nes_box_art/super-spy-hunter.webp",
    "Bubble Bobble": "images/nes_box_art/bubble-bobble.webp",
    "Dungeon Magic": "images/nes_box_art/dungeon-magic.webp",
    "Indiana Jones and the Last Crusade": "images/nes_box_art/indiana-jones-and-the-last-crusade.webp",
    "Jetsons": "images/nes_box_art/jetsons-the-cogswell-s-caper.webp",
    "Kick Master": "images/nes_box_art/kickmaster.webp",
    "Legend of Kage": "images/nes_box_art/legend-of-kage-the.webp",
    "Little Samson": "images/nes_box_art/little-samson.webp",
    "Panic Restaurant": "images/nes_box_art/panic-restaurant.webp",
    "Power Blade 2": "images/nes_box_art/power-blade-2.webp",
    "Power Blade": "images/nes_box_art/power-blade.webp",
    "Sky Shark": "images/nes_box_art/sky-shark.webp",
    "Target Renegade": "images/nes_box_art/target-renegade.webp",
    "8 Eyes": "images/nes_box_art/8-eyes.webp",
    "Burai Fighter": "images/nes_box_art/burai-fighter.webp",
    "Magician": "images/nes_box_art/magician.webp",
    "Mappyland": "images/nes_box_art/mappyland.webp",
    "Star Soldier": "images/nes_box_art/star-soldier.webp",
    "Crash n the Boys Street Challenge": "images/nes_box_art/crash-n-the-boys-street-challenge.webp",
    "River City Ransom": "images/nes_box_art/river-city-ransom.webp",
    "Mighty Bombjack": "images/nes_box_art/mighty-bomb-jack.webp",
    "Ninja Gaiden 2": "images/nes_box_art/ninja-gaiden-ii.webp",
    "Ninja Gaiden 3": "images/nes_box_art/ninja-gaiden-iii.webp",
    "Ninja Gaiden": "images/nes_box_art/ninja-gaiden.webp",
    "Rygar": "images/nes_box_art/rygar.webp",
    "Solomons Key": "images/nes_box_art/solomon-s-key.webp",
    "Tecmo Bowl": "images/nes_box_art/tecmo-bowl.webp",
    "Tecmo Cup Soccer Game": "images/nes_box_art/tecmo-cup-soccer-game.webp",
    "Tecmo World Wrestling": "images/nes_box_art/tecmo-world-wrestling.webp",
    "Fantasy Zone NES": "images/nes_box_art/fantasy-zone.webp",
    "Klax": "images/nes_box_art/klax.webp",
    "RBI Baseball": "images/nes_box_art/r-b-i-baseball.webp",
    "Tetris Tengen": "images/nes_box_art/tetris.webp",
    "Attack of the Killer Tomatoes": "images/nes_box_art/attack-of-the-killer-tomatoes.webp",
    "Battletoads and Double Dragon": "images/nes_box_art/battletoads-double-dragon.webp",
    "Battletoads": "images/nes_box_art/battletoads.webp",
    "Double Dragon": "images/nes_box_art/double-dragon.webp",
    "Magic Johnsons Fast Break": "images/nes_box_art/magic-johnson-s-fast-break.webp",
    "Solar Jetman": "images/nes_box_art/solar-jetman-hunt-for-the-golden-warship.webp",
    "Bump N Jump": "images/nes_box_art/bump-n-jump.webp",
    "Krion Conquest": "images/nes_box_art/krion-conquest-the.webp",
    "Jungle Book": "images/nes_box_art/jungle-book-the.webp",
    "MC Kids": "images/nes_box_art/m-c-kids.webp",
    "Silver Surfer": "images/nes_box_art/silver-sufer.webp"
});
