// Auto-generated NES game library — 506 entries
// Source: NES-Gamemusic/ directory
'use strict';

const NSF_LIBRARY = [
    { title: 'Armed Dragon Fantasy Villgust', publisher: 'Angel', region: 'Famicom', file: 'NES-Gamemusic/Famicom/Angel/Armed_Dragon_Fantasy_Villgust.nsf' },
    { title: 'Choujin Sentai Jetman', publisher: 'Angel', region: 'Famicom', file: 'NES-Gamemusic/Famicom/Angel/Choujin_Sentai_Jetman.nsf' },
    { title: 'Astro Robo Sasa', publisher: 'Ascii', region: 'Famicom', file: 'NES-Gamemusic/Famicom/Ascii/Astro_Robo_Sasa.nsf' },
    { title: 'Bokosuka Wars', publisher: 'Ascii', region: 'Famicom', file: 'NES-Gamemusic/Famicom/Ascii/Bokosuka_Wars.nsf' },
    { title: 'Itadaki Street', publisher: 'Ascii', region: 'Famicom', file: 'NES-Gamemusic/Famicom/Ascii/Itadaki_Street.nsf' },
    { title: 'Wizardry 3', publisher: 'Ascii', region: 'Famicom', file: 'NES-Gamemusic/Famicom/Ascii/Wizardry_3.nsf' },
    { title: 'Hyaku no Sekai no Monogatari', publisher: 'Ask Kodansha', region: 'Famicom', file: 'NES-Gamemusic/Famicom/Ask_Kodansha/Hyaku_no_Sekai_no_Monogatari.nsf' },
    { title: 'Maten Douji', publisher: 'Asmik', region: 'Famicom', file: 'NES-Gamemusic/Famicom/Asmik/Maten_Douji.nsf' },
    { title: 'Dragon Ball 2', publisher: 'Bandai', region: 'Famicom', file: 'NES-Gamemusic/Famicom/Bandai/Dragon_Ball_2.nsf' },
    { title: 'Dragon Ball 3', publisher: 'Bandai', region: 'Famicom', file: 'NES-Gamemusic/Famicom/Bandai/Dragon_Ball_3.nsf' },
    { title: 'Gegege No Kitarou 2', publisher: 'Bandai', region: 'Famicom', file: 'NES-Gamemusic/Famicom/Bandai/Gegege_No_Kitarou_2.nsf' },
    { title: 'Kamen Rider Club', publisher: 'Bandai', region: 'Famicom', file: 'NES-Gamemusic/Famicom/Bandai/Kamen_Rider_Club.nsf' },
    { title: 'Last Armageddon', publisher: 'Bandai', region: 'Famicom', file: 'NES-Gamemusic/Famicom/Bandai/Last_Armageddon.nsf' },
    { title: 'Obake no Q tarou', publisher: 'Bandai', region: 'Famicom', file: 'NES-Gamemusic/Famicom/Bandai/Obake_no_Q_tarou.nsf' },
    { title: 'Pocket Zaurus Juohken no Nazo', publisher: 'Bandai', region: 'Famicom', file: 'NES-Gamemusic/Famicom/Bandai/Pocket_Zaurus_Juohken_no_Nazo.nsf' },
    { title: 'Zeta Gundam Hot Scramble', publisher: 'Bandai', region: 'Famicom', file: 'NES-Gamemusic/Famicom/Bandai/Zeta_Gundam_Hot_Scramble.nsf' },
    { title: 'Daisenryaku', publisher: 'Bothtec', region: 'Famicom', file: 'NES-Gamemusic/Famicom/Bothtec/Daisenryaku.nsf' },
    { title: 'Relics Ankoku Yousai', publisher: 'Bothtec', region: 'Famicom', file: 'NES-Gamemusic/Famicom/Bothtec/Relics_Ankoku_Yousai.nsf' },
    { title: 'BPS Tetris', publisher: 'BPS', region: 'Famicom', file: 'NES-Gamemusic/Famicom/BPS/BPS_Tetris.nsf' },
    { title: 'Tetris 2 and Bombliss', publisher: 'BPS', region: 'Famicom', file: 'NES-Gamemusic/Famicom/BPS/Tetris_2_and_Bombliss.nsf' },
    { title: 'Makaijima', publisher: 'Capcom', region: 'Famicom', file: 'NES-Gamemusic/Famicom/Capcom/Makaijima.nsf' },
    { title: 'RockBoard', publisher: 'Capcom', region: 'Famicom', file: 'NES-Gamemusic/Famicom/Capcom/RockBoard.nsf' },
    { title: 'Sweet Home', publisher: 'Capcom', region: 'Famicom', file: 'NES-Gamemusic/Famicom/Capcom/Sweet_Home.nsf' },
    { title: 'Tenchi o Kurau II', publisher: 'Capcom', region: 'Famicom', file: 'NES-Gamemusic/Famicom/Capcom/Tenchi_o_Kurau_II.nsf' },
    { title: 'Hello Kitty World', publisher: 'Character Soft', region: 'Famicom', file: 'NES-Gamemusic/Famicom/Character_Soft/Hello_Kitty_World.nsf' },
    { title: '1999', publisher: 'Coconuts Japan', region: 'Famicom', file: 'NES-Gamemusic/Famicom/Coconuts_Japan/1999.nsf' },
    { title: 'B Wing', publisher: 'Data East', region: 'Famicom', file: 'NES-Gamemusic/Famicom/Data_East/B_Wing.nsf' },
    { title: 'Daikaijuu Deburas', publisher: 'Data East', region: 'Famicom', file: 'NES-Gamemusic/Famicom/Data_East/Daikaijuu_Deburas.nsf' },
    { title: 'Dark Lord', publisher: 'Data East', region: 'Famicom', file: 'NES-Gamemusic/Famicom/Data_East/Dark_Lord.nsf' },
    { title: 'Hercules no Eikou 2', publisher: 'Data East', region: 'Famicom', file: 'NES-Gamemusic/Famicom/Data_East/Hercules_no_Eikou_2.nsf' },
    { title: 'Hercules no Eikou', publisher: 'Data East', region: 'Famicom', file: 'NES-Gamemusic/Famicom/Data_East/Hercules_no_Eikou.nsf' },
    { title: 'Kiken na Futari', publisher: 'Data East', region: 'Famicom', file: 'NES-Gamemusic/Famicom/Data_East/Kiken_na_Futari.nsf' },
    { title: 'Metal Max', publisher: 'Data East', region: 'Famicom', file: 'NES-Gamemusic/Famicom/Data_East/Metal_Max.nsf' },
    { title: 'Shinjuku Chuokoen Satsujinjiken', publisher: 'Data East', region: 'Famicom', file: 'NES-Gamemusic/Famicom/Data_East/Shinjuku_Chuokoen_Satsujinjiken.nsf' },
    { title: 'Toki no Sugiyuku mama ni', publisher: 'Data East', region: 'Famicom', file: 'NES-Gamemusic/Famicom/Data_East/Toki_no_Sugiyuku_mama_ni.nsf' },
    { title: 'Yokohamako Renzokusatsujinjiken', publisher: 'Data East', region: 'Famicom', file: 'NES-Gamemusic/Famicom/Data_East/Yokohamako_Renzokusatsujinjiken.nsf' },
    { title: 'Flappy', publisher: 'db Soft', region: 'Famicom', file: 'NES-Gamemusic/Famicom/db_Soft/Flappy.nsf' },
    { title: 'Volgard II', publisher: 'db Soft', region: 'Famicom', file: 'NES-Gamemusic/Famicom/db_Soft/Volgard_II.nsf' },
    { title: 'Akagawa Jirou no Yuurei Ressha', publisher: 'Enix', region: 'Famicom', file: 'NES-Gamemusic/Famicom/Enix/Akagawa_Jirou_no_Yuurei_Ressha.nsf' },
    { title: 'Just Breed', publisher: 'Enix', region: 'Famicom', file: 'NES-Gamemusic/Famicom/Enix/Just_Breed.nsf' },
    { title: 'Doraemon Gigzombie no Gyakushuu', publisher: 'Epoch', region: 'Famicom', file: 'NES-Gamemusic/Famicom/Epoch/Doraemon_Gigzombie_no_Gyakushuu.nsf' },
    { title: 'Shoukoushi  Ceddie', publisher: 'Fuji TV', region: 'Famicom', file: 'NES-Gamemusic/Famicom/Fuji_TV/Shoukoushi _Ceddie.nsf' },
    { title: 'Uchuu Keibitai SDF', publisher: 'Hal Lab', region: 'Famicom', file: 'NES-Gamemusic/Famicom/Hal_Lab/Uchuu_Keibitai_SDF.nsf' },
    { title: 'Moon Crystal', publisher: 'Hector', region: 'Famicom', file: 'NES-Gamemusic/Famicom/Hector/Moon_Crystal.nsf' },
    { title: 'Zombie Hunter', publisher: 'High Score', region: 'Famicom', file: 'NES-Gamemusic/Famicom/High_Score/Zombie_Hunter.nsf' },
    { title: 'Over Horizon', publisher: 'Hot B', region: 'Famicom', file: 'NES-Gamemusic/Famicom/Hot_B/Over_Horizon.nsf' },
    { title: 'Bikkuriman World', publisher: 'Hudson Soft', region: 'Famicom', file: 'NES-Gamemusic/Famicom/Hudson_Soft/Bikkuriman_World.nsf' },
    { title: 'Challenger', publisher: 'Hudson Soft', region: 'Famicom', file: 'NES-Gamemusic/Famicom/Hudson_Soft/Challenger.nsf' },
    { title: 'Doraemon', publisher: 'Hudson Soft', region: 'Famicom', file: 'NES-Gamemusic/Famicom/Hudson_Soft/Doraemon.nsf' },
    { title: 'Majin Eiyuuden Wataru Gaiden', publisher: 'Hudson Soft', region: 'Famicom', file: 'NES-Gamemusic/Famicom/Hudson_Soft/Majin_Eiyuuden_Wataru_Gaiden.nsf' },
    { title: 'Ninja Hattori Kun', publisher: 'Hudson Soft', region: 'Famicom', file: 'NES-Gamemusic/Famicom/Hudson_Soft/Ninja_Hattori_Kun.nsf' },
    { title: 'Nuts and Milk', publisher: 'Hudson Soft', region: 'Famicom', file: 'NES-Gamemusic/Famicom/Hudson_Soft/Nuts_and_Milk.nsf' },
    { title: 'Pooyan', publisher: 'Hudson Soft', region: 'Famicom', file: 'NES-Gamemusic/Famicom/Hudson_Soft/Pooyan.nsf' },
    { title: 'Star Force FC', publisher: 'Hudson Soft', region: 'Famicom', file: 'NES-Gamemusic/Famicom/Hudson_Soft/Star_Force_FC.nsf' },
    { title: 'Armadillo', publisher: 'IGS', region: 'Famicom', file: 'NES-Gamemusic/Famicom/IGS/Armadillo.nsf' },
    { title: 'J League Fighting Soccer', publisher: 'IGS', region: 'Famicom', file: 'NES-Gamemusic/Famicom/IGS/J_League_Fighting_Soccer.nsf' },
    { title: 'Robokko Wars', publisher: 'IGS', region: 'Famicom', file: 'NES-Gamemusic/Famicom/IGS/Robokko_Wars.nsf' },
    { title: 'Shancara', publisher: 'IGS', region: 'Famicom', file: 'NES-Gamemusic/Famicom/IGS/Shancara.nsf' },
    { title: 'Argus', publisher: 'Jaleco', region: 'Famicom', file: 'NES-Gamemusic/Famicom/Jaleco/Argus.nsf' },
    { title: 'Big Challenge Dogfight Spirit', publisher: 'Jaleco', region: 'Famicom', file: 'NES-Gamemusic/Famicom/Jaleco/Big_Challenge_Dogfight_Spirit.nsf' },
    { title: 'Bio Senshi Dan', publisher: 'Jaleco', region: 'Famicom', file: 'NES-Gamemusic/Famicom/Jaleco/Bio_Senshi_Dan.nsf' },
    { title: 'Pizza Pop', publisher: 'Jaleco', region: 'Famicom', file: 'NES-Gamemusic/Famicom/Jaleco/Pizza_Pop.nsf' },
    { title: 'Rodland', publisher: 'Jaleco', region: 'Famicom', file: 'NES-Gamemusic/Famicom/Jaleco/Rodland.nsf' },
    { title: 'Toukon Club', publisher: 'Jaleco', region: 'Famicom', file: 'NES-Gamemusic/Famicom/Jaleco/Toukon_Club.nsf' },
    { title: 'Sted', publisher: 'KAC', region: 'Famicom', file: 'NES-Gamemusic/Famicom/KAC/Sted.nsf' },
    { title: 'Jesus', publisher: 'King Records', region: 'Famicom', file: 'NES-Gamemusic/Famicom/King_Records/Jesus.nsf' },
    { title: 'Ai Senshi Nicol', publisher: 'Konami', region: 'Famicom', file: 'NES-Gamemusic/Famicom/Konami/Ai_Senshi_Nicol.nsf' },
    { title: 'Akai Yousai', publisher: 'Konami', region: 'Famicom', file: 'NES-Gamemusic/Famicom/Konami/Akai_Yousai.nsf' },
    { title: 'Akumajou Densetsu', publisher: 'Konami', region: 'Famicom', file: 'NES-Gamemusic/Famicom/Konami/Akumajou_Densetsu.nsf' },
    { title: 'Almana no Kiseki', publisher: 'Konami', region: 'Famicom', file: 'NES-Gamemusic/Famicom/Konami/Almana_no_Kiseki.nsf' },
    { title: 'Antarctic Adventure', publisher: 'Konami', region: 'Famicom', file: 'NES-Gamemusic/Famicom/Konami/Antarctic_Adventure.nsf' },
    { title: 'Bio Miracle Boku tte Upa', publisher: 'Konami', region: 'Famicom', file: 'NES-Gamemusic/Famicom/Konami/Bio_Miracle_Boku_tte_Upa.nsf' },
    { title: 'Boku Dracula Kun', publisher: 'Konami', region: 'Famicom', file: 'NES-Gamemusic/Famicom/Konami/Boku_Dracula_Kun.nsf' },
    { title: 'Cosmic Wars', publisher: 'Konami', region: 'Famicom', file: 'NES-Gamemusic/Famicom/Konami/Cosmic_Wars.nsf' },
    { title: 'Crisis Force', publisher: 'Konami', region: 'Famicom', file: 'NES-Gamemusic/Famicom/Konami/Crisis_Force.nsf' },
    { title: 'Dragon Scroll', publisher: 'Konami', region: 'Famicom', file: 'NES-Gamemusic/Famicom/Konami/Dragon_Scroll.nsf' },
    { title: 'Esper Dream 2', publisher: 'Konami', region: 'Famicom', file: 'NES-Gamemusic/Famicom/Konami/Esper_Dream_2.nsf' },
    { title: 'Esper Dream', publisher: 'Konami', region: 'Famicom', file: 'NES-Gamemusic/Famicom/Konami/Esper_Dream.nsf' },
    { title: 'Exciting Basket', publisher: 'Konami', region: 'Famicom', file: 'NES-Gamemusic/Famicom/Konami/Exciting_Basket.nsf' },
    { title: 'F1 Sensation', publisher: 'Konami', region: 'Famicom', file: 'NES-Gamemusic/Famicom/Konami/F1_Sensation.nsf' },
    { title: 'Falsion', publisher: 'Konami', region: 'Famicom', file: 'NES-Gamemusic/Famicom/Konami/Falsion.nsf' },
    { title: 'Ganbare Goemon 2', publisher: 'Konami', region: 'Famicom', file: 'NES-Gamemusic/Famicom/Konami/Ganbare_Goemon_2.nsf' },
    { title: 'Ganbare Goemon', publisher: 'Konami', region: 'Famicom', file: 'NES-Gamemusic/Famicom/Konami/Ganbare_Goemon.nsf' },
    { title: 'Getsufuu Maden', publisher: 'Konami', region: 'Famicom', file: 'NES-Gamemusic/Famicom/Konami/Getsufuu_Maden.nsf' },
    { title: 'Goonies', publisher: 'Konami', region: 'Famicom', file: 'NES-Gamemusic/Famicom/Konami/Goonies.nsf' },
    { title: 'Gradius II', publisher: 'Konami', region: 'Famicom', file: 'NES-Gamemusic/Famicom/Konami/Gradius_II.nsf' },
    { title: 'Hi no Tori', publisher: 'Konami', region: 'Famicom', file: 'NES-Gamemusic/Famicom/Konami/Hi_no_Tori.nsf' },
    { title: 'King Kong 2', publisher: 'Konami', region: 'Famicom', file: 'NES-Gamemusic/Famicom/Konami/King_Kong_2.nsf' },
    { title: 'Lagrange Point', publisher: 'Konami', region: 'Famicom', file: 'NES-Gamemusic/Famicom/Konami/Lagrange_Point.nsf' },
    { title: 'Madara', publisher: 'Konami', region: 'Famicom', file: 'NES-Gamemusic/Famicom/Konami/Madara.nsf' },
    { title: 'Maze of Galious 2', publisher: 'Konami', region: 'Famicom', file: 'NES-Gamemusic/Famicom/Konami/Maze_of_Galious_2.nsf' },
    { title: 'Meikyuu Jiin Dababa', publisher: 'Konami', region: 'Famicom', file: 'NES-Gamemusic/Famicom/Konami/Meikyuu_Jiin_Dababa.nsf' },
    { title: 'Nazo no Kabe', publisher: 'Konami', region: 'Famicom', file: 'NES-Gamemusic/Famicom/Konami/Nazo_no_Kabe.nsf' },
    { title: 'Parodius Da', publisher: 'Konami', region: 'Famicom', file: 'NES-Gamemusic/Famicom/Konami/Parodius_Da.nsf' },
    { title: 'Quarth', publisher: 'Konami', region: 'Famicom', file: 'NES-Gamemusic/Famicom/Konami/Quarth.nsf' },
    { title: 'Rampart', publisher: 'Konami', region: 'Famicom', file: 'NES-Gamemusic/Famicom/Konami/Rampart.nsf' },
    { title: 'Risa no Yousei Densetsu', publisher: 'Konami', region: 'Famicom', file: 'NES-Gamemusic/Famicom/Konami/Risa_no_Yousei_Densetsu.nsf' },
    { title: 'Twinbee 3', publisher: 'Konami', region: 'Famicom', file: 'NES-Gamemusic/Famicom/Konami/Twinbee_3.nsf' },
    { title: 'Twinbee', publisher: 'Konami', region: 'Famicom', file: 'NES-Gamemusic/Famicom/Konami/Twinbee.nsf' },
    { title: 'Wai Wai World 2', publisher: 'Konami', region: 'Famicom', file: 'NES-Gamemusic/Famicom/Konami/Wai_Wai_World_2.nsf' },
    { title: 'Wai Wai World', publisher: 'Konami', region: 'Famicom', file: 'NES-Gamemusic/Famicom/Konami/Wai_Wai_World.nsf' },
    { title: 'Yie Ar Kung Fu', publisher: 'Konami', region: 'Famicom', file: 'NES-Gamemusic/Famicom/Konami/Yie_Ar_Kung_Fu.nsf' },
    { title: 'Yume Penguin Monogatari', publisher: 'Konami', region: 'Famicom', file: 'NES-Gamemusic/Famicom/Konami/Yume_Penguin_Monogatari.nsf' },
    { title: 'Okhotsk ni Shoyu', publisher: 'Login Soft', region: 'Famicom', file: 'NES-Gamemusic/Famicom/Login_Soft/Okhotsk_ni_Shoyu.nsf' },
    { title: 'Doki Doki Yuuenchi', publisher: 'Misc', region: 'Famicom', file: 'NES-Gamemusic/Famicom/Misc/Doki_Doki_Yuuenchi.nsf' },
    { title: 'Somari', publisher: 'Misc', region: 'Famicom', file: 'NES-Gamemusic/Famicom/Misc/Somari.nsf' },
    { title: 'Chou Jikuu Yousai Macross', publisher: 'Namco', region: 'Famicom', file: 'NES-Gamemusic/Famicom/Namco/Chou_Jikuu_Yousai_Macross.nsf' },
    { title: 'Dragon Buster II', publisher: 'Namco', region: 'Famicom', file: 'NES-Gamemusic/Famicom/Namco/Dragon_Buster_II.nsf' },
    { title: 'Dragon Buster', publisher: 'Namco', region: 'Famicom', file: 'NES-Gamemusic/Famicom/Namco/Dragon_Buster.nsf' },
    { title: 'Erika to Satoru no Yumebouken', publisher: 'Namco', region: 'Famicom', file: 'NES-Gamemusic/Famicom/Namco/Erika_to_Satoru_no_Yumebouken.nsf' },
    { title: 'Family Circuit', publisher: 'Namco', region: 'Famicom', file: 'NES-Gamemusic/Famicom/Namco/Family_Circuit.nsf' },
    { title: 'Final Lap', publisher: 'Namco', region: 'Famicom', file: 'NES-Gamemusic/Famicom/Namco/Final_Lap.nsf' },
    { title: 'Heisei Tensai Bakabon', publisher: 'Namco', region: 'Famicom', file: 'NES-Gamemusic/Famicom/Namco/Heisei_Tensai_Bakabon.nsf' },
    { title: 'Kaijuu Monogatari', publisher: 'Namco', region: 'Famicom', file: 'NES-Gamemusic/Famicom/Namco/Kaijuu_Monogatari.nsf' },
    { title: 'Kai no Bouken', publisher: 'Namco', region: 'Famicom', file: 'NES-Gamemusic/Famicom/Namco/Kai_no_Bouken.nsf' },
    { title: 'Keru Naguuru', publisher: 'Namco', region: 'Famicom', file: 'NES-Gamemusic/Famicom/Namco/Keru_Naguuru.nsf' },
    { title: 'King of Kings', publisher: 'Namco', region: 'Famicom', file: 'NES-Gamemusic/Famicom/Namco/King_of_Kings.nsf' },
    { title: 'Lasalle Ishii no Childs Quest', publisher: 'Namco', region: 'Famicom', file: 'NES-Gamemusic/Famicom/Namco/Lasalle_Ishii_no_Childs_Quest.nsf' },
    { title: 'Mappy Kids', publisher: 'Namco', region: 'Famicom', file: 'NES-Gamemusic/Famicom/Namco/Mappy_Kids.nsf' },
    { title: 'Megami Tensei II', publisher: 'Namco', region: 'Famicom', file: 'NES-Gamemusic/Famicom/Namco/Megami_Tensei_II.nsf' },
    { title: 'Megami Tensei', publisher: 'Namco', region: 'Famicom', file: 'NES-Gamemusic/Famicom/Namco/Megami_Tensei.nsf' },
    { title: 'Rolling Thunder', publisher: 'Namco', region: 'Famicom', file: 'NES-Gamemusic/Famicom/Namco/Rolling_Thunder.nsf' },
    { title: 'Sangokushi 2', publisher: 'Namco', region: 'Famicom', file: 'NES-Gamemusic/Famicom/Namco/Sangokushi_2.nsf' },
    { title: 'Sanma no Meitantei', publisher: 'Namco', region: 'Famicom', file: 'NES-Gamemusic/Famicom/Namco/Sanma_no_Meitantei.nsf' },
    { title: 'Skykid', publisher: 'Namco', region: 'Famicom', file: 'NES-Gamemusic/Famicom/Namco/Skykid.nsf' },
    { title: 'Splatterhouse', publisher: 'Namco', region: 'Famicom', file: 'NES-Gamemusic/Famicom/Namco/Splatterhouse.nsf' },
    { title: 'Star Luster', publisher: 'Namco', region: 'Famicom', file: 'NES-Gamemusic/Famicom/Namco/Star_Luster.nsf' },
    { title: 'Super Xevious', publisher: 'Namco', region: 'Famicom', file: 'NES-Gamemusic/Famicom/Namco/Super_Xevious.nsf' },
    { title: 'Top Striker', publisher: 'Namco', region: 'Famicom', file: 'NES-Gamemusic/Famicom/Namco/Top_Striker.nsf' },
    { title: 'Tower of Babel', publisher: 'Namco', region: 'Famicom', file: 'NES-Gamemusic/Famicom/Namco/Tower_of_Babel.nsf' },
    { title: 'Tower of Druaga', publisher: 'Namco', region: 'Famicom', file: 'NES-Gamemusic/Famicom/Namco/Tower_of_Druaga.nsf' },
    { title: 'Valkyrie No Bouken', publisher: 'Namco', region: 'Famicom', file: 'NES-Gamemusic/Famicom/Namco/Valkyrie_No_Bouken.nsf' },
    { title: 'Wagyan Land 2', publisher: 'Namco', region: 'Famicom', file: 'NES-Gamemusic/Famicom/Namco/Wagyan_Land_2.nsf' },
    { title: 'Wagyan Land 3', publisher: 'Namco', region: 'Famicom', file: 'NES-Gamemusic/Famicom/Namco/Wagyan_Land_3.nsf' },
    { title: 'Wagyan Land', publisher: 'Namco', region: 'Famicom', file: 'NES-Gamemusic/Famicom/Namco/Wagyan_Land.nsf' },
    { title: 'Youkai Douchuuki', publisher: 'Namco', region: 'Famicom', file: 'NES-Gamemusic/Famicom/Namco/Youkai_Douchuuki.nsf' },
    { title: 'Chaos World', publisher: 'Natsume', region: 'Famicom', file: 'NES-Gamemusic/Famicom/Natsume/Chaos_World.nsf' },
    { title: 'Chugoku Jangshi Story Tongpoo', publisher: 'Natsume', region: 'Famicom', file: 'NES-Gamemusic/Famicom/Natsume/Chugoku_Jangshi_Story_Tongpoo.nsf' },
    { title: 'Final Mission', publisher: 'Natsume', region: 'Famicom', file: 'NES-Gamemusic/Famicom/Natsume/Final_Mission.nsf' },
    { title: 'Recca', publisher: 'Naxat Soft', region: 'Famicom', file: 'NES-Gamemusic/Famicom/Naxat_Soft/Recca.nsf' },
    { title: 'Castlequest', publisher: 'Nexoft', region: 'Famicom', file: 'NES-Gamemusic/Famicom/Nexoft/Castlequest.nsf' },
    { title: 'Cosmo Police Galivan', publisher: 'Nichibutsu', region: 'Famicom', file: 'NES-Gamemusic/Famicom/Nichibutsu/Cosmo_Police_Galivan.nsf' },
    { title: 'Devil World', publisher: 'Nintendo', region: 'Famicom', file: 'NES-Gamemusic/Famicom/Nintendo/Devil_World.nsf' },
    { title: 'Disk System BIOS', publisher: 'Nintendo', region: 'Famicom', file: 'NES-Gamemusic/Famicom/Nintendo/Disk_System_BIOS.nsf' },
    { title: 'F1 Race', publisher: 'Nintendo', region: 'Famicom', file: 'NES-Gamemusic/Famicom/Nintendo/F1_Race.nsf' },
    { title: 'Famicom Tantei Club 2', publisher: 'Nintendo', region: 'Famicom', file: 'NES-Gamemusic/Famicom/Nintendo/Famicom_Tantei_Club_2.nsf' },
    { title: 'Famicom Tantei Club', publisher: 'Nintendo', region: 'Famicom', file: 'NES-Gamemusic/Famicom/Nintendo/Famicom_Tantei_Club.nsf' },
    { title: 'Famicom Wars', publisher: 'Nintendo', region: 'Famicom', file: 'NES-Gamemusic/Famicom/Nintendo/Famicom_Wars.nsf' },
    { title: 'Fire Emblem Gaiden', publisher: 'Nintendo', region: 'Famicom', file: 'NES-Gamemusic/Famicom/Nintendo/Fire_Emblem_Gaiden.nsf' },
    { title: 'Fire Emblem', publisher: 'Nintendo', region: 'Famicom', file: 'NES-Gamemusic/Famicom/Nintendo/Fire_Emblem.nsf' },
    { title: 'Ice Climber FDS', publisher: 'Nintendo', region: 'Famicom', file: 'NES-Gamemusic/Famicom/Nintendo/Ice_Climber_FDS.nsf' },
    { title: 'Joy Mecha Fight', publisher: 'Nintendo', region: 'Famicom', file: 'NES-Gamemusic/Famicom/Nintendo/Joy_Mecha_Fight.nsf' },
    { title: 'Link no Bouken', publisher: 'Nintendo', region: 'Famicom', file: 'NES-Gamemusic/Famicom/Nintendo/Link_no_Bouken.nsf' },
    { title: 'Mario Open Golf', publisher: 'Nintendo', region: 'Famicom', file: 'NES-Gamemusic/Famicom/Nintendo/Mario_Open_Golf.nsf' },
    { title: 'Metroid FDS', publisher: 'Nintendo', region: 'Famicom', file: 'NES-Gamemusic/Famicom/Nintendo/Metroid_FDS.nsf' },
    { title: 'Nazo no Murasamejou', publisher: 'Nintendo', region: 'Famicom', file: 'NES-Gamemusic/Famicom/Nintendo/Nazo_no_Murasamejou.nsf' },
    { title: 'Palutena no Kagami', publisher: 'Nintendo', region: 'Famicom', file: 'NES-Gamemusic/Famicom/Nintendo/Palutena_no_Kagami.nsf' },
    { title: 'Pro Wrestling', publisher: 'Nintendo', region: 'Famicom', file: 'NES-Gamemusic/Famicom/Nintendo/Pro_Wrestling.nsf' },
    { title: 'Shin Onigashima', publisher: 'Nintendo', region: 'Famicom', file: 'NES-Gamemusic/Famicom/Nintendo/Shin_Onigashima.nsf' },
    { title: 'Vs Excitebike FDS', publisher: 'Nintendo', region: 'Famicom', file: 'NES-Gamemusic/Famicom/Nintendo/Vs_Excitebike_FDS.nsf' },
    { title: 'Yuuyuuki', publisher: 'Nintendo', region: 'Famicom', file: 'NES-Gamemusic/Famicom/Nintendo/Yuuyuuki.nsf' },
    { title: 'Zelda no Densetsu', publisher: 'Nintendo', region: 'Famicom', file: 'NES-Gamemusic/Famicom/Nintendo/Zelda_no_Densetsu.nsf' },
    { title: 'Silva Saga', publisher: 'Seta', region: 'Famicom', file: 'NES-Gamemusic/Famicom/Seta/Silva_Saga.nsf' },
    { title: 'Musashi no Bouken', publisher: 'Sigma', region: 'Famicom', file: 'NES-Gamemusic/Famicom/Sigma/Musashi_no_Bouken.nsf' },
    { title: 'Time Zone', publisher: 'Sigma', region: 'Famicom', file: 'NES-Gamemusic/Famicom/Sigma/Time_Zone.nsf' },
    { title: 'Final Fantasy 2', publisher: 'Square', region: 'Famicom', file: 'NES-Gamemusic/Famicom/Square/Final_Fantasy_2.nsf' },
    { title: 'Final Fantasy 3', publisher: 'Square', region: 'Famicom', file: 'NES-Gamemusic/Famicom/Square/Final_Fantasy_3.nsf' },
    { title: 'Hanjuku Hero', publisher: 'Square', region: 'Famicom', file: 'NES-Gamemusic/Famicom/Square/Hanjuku_Hero.nsf' },
    { title: 'After Burner II', publisher: 'Sunsoft', region: 'Famicom', file: 'NES-Gamemusic/Famicom/Sunsoft/After_Burner_II.nsf' },
    { title: 'Atlantis no Nazo', publisher: 'Sunsoft', region: 'Famicom', file: 'NES-Gamemusic/Famicom/Sunsoft/Atlantis_no_Nazo.nsf' },
    { title: 'Dodge Danpei 2', publisher: 'Sunsoft', region: 'Famicom', file: 'NES-Gamemusic/Famicom/Sunsoft/Dodge_Danpei_2.nsf' },
    { title: 'Dodge Danpei', publisher: 'Sunsoft', region: 'Famicom', file: 'NES-Gamemusic/Famicom/Sunsoft/Dodge_Danpei.nsf' },
    { title: 'Fantasy Zone 2', publisher: 'Sunsoft', region: 'Famicom', file: 'NES-Gamemusic/Famicom/Sunsoft/Fantasy_Zone_2.nsf' },
    { title: 'Fantasy Zone FC', publisher: 'Sunsoft', region: 'Famicom', file: 'NES-Gamemusic/Famicom/Sunsoft/Fantasy_Zone_FC.nsf' },
    { title: 'Gimmick', publisher: 'Sunsoft', region: 'Famicom', file: 'NES-Gamemusic/Famicom/Sunsoft/Gimmick.nsf' },
    { title: 'Hebereke', publisher: 'Sunsoft', region: 'Famicom', file: 'NES-Gamemusic/Famicom/Sunsoft/Hebereke.nsf' },
    { title: 'Mito Koumon', publisher: 'Sunsoft', region: 'Famicom', file: 'NES-Gamemusic/Famicom/Sunsoft/Mito_Koumon.nsf' },
    { title: 'Nante tta tte Baseball', publisher: 'Sunsoft', region: 'Famicom', file: 'NES-Gamemusic/Famicom/Sunsoft/Nante_tta_tte_Baseball.nsf' },
    { title: 'Shanghai 2', publisher: 'Sunsoft', region: 'Famicom', file: 'NES-Gamemusic/Famicom/Sunsoft/Shanghai_2.nsf' },
    { title: 'Shanghai', publisher: 'Sunsoft', region: 'Famicom', file: 'NES-Gamemusic/Famicom/Sunsoft/Shanghai.nsf' },
    { title: 'Toukaidou 53 tsugi', publisher: 'Sunsoft', region: 'Famicom', file: 'NES-Gamemusic/Famicom/Sunsoft/Toukaidou_53_tsugi.nsf' },
    { title: 'Wing of Madoola', publisher: 'Sunsoft', region: 'Famicom', file: 'NES-Gamemusic/Famicom/Sunsoft/Wing_of_Madoola.nsf' },
    { title: 'Chase HQ', publisher: 'Taito', region: 'Famicom', file: 'NES-Gamemusic/Famicom/Taito/Chase_HQ.nsf' },
    { title: 'Don Doko Don 2', publisher: 'Taito', region: 'Famicom', file: 'NES-Gamemusic/Famicom/Taito/Don_Doko_Don_2.nsf' },
    { title: 'Don Doko Don', publisher: 'Taito', region: 'Famicom', file: 'NES-Gamemusic/Famicom/Taito/Don_Doko_Don.nsf' },
    { title: 'Insector X', publisher: 'Taito', region: 'Famicom', file: 'NES-Gamemusic/Famicom/Taito/Insector_X.nsf' },
    { title: 'KikiKaikai', publisher: 'Taito', region: 'Famicom', file: 'NES-Gamemusic/Famicom/Taito/KikiKaikai.nsf' },
    { title: 'Minelvaton Saga', publisher: 'Taito', region: 'Famicom', file: 'NES-Gamemusic/Famicom/Taito/Minelvaton_Saga.nsf' },
    { title: 'SD Keiji Blader', publisher: 'Taito', region: 'Famicom', file: 'NES-Gamemusic/Famicom/Taito/SD_Keiji_Blader.nsf' },
    { title: 'Takeshi no Chousenjou', publisher: 'Taito', region: 'Famicom', file: 'NES-Gamemusic/Famicom/Taito/Takeshi_no_Chousenjou.nsf' },
    { title: 'Yuu Maze', publisher: 'Taito', region: 'Famicom', file: 'NES-Gamemusic/Famicom/Taito/Yuu_Maze.nsf' },
    { title: 'Transformers Convoy no Nazo', publisher: 'Takara', region: 'Famicom', file: 'NES-Gamemusic/Famicom/Takara/Transformers_Convoy_no_Nazo.nsf' },
    { title: 'Cocoron', publisher: 'Takeru', region: 'Famicom', file: 'NES-Gamemusic/Famicom/Takeru/Cocoron.nsf' },
    { title: 'Downtown Nekketsu Koushinkyoku', publisher: 'Technos', region: 'Famicom', file: 'NES-Gamemusic/Famicom/Technos/Downtown_Nekketsu_Koushinkyoku.nsf' },
    { title: 'Kunio no Jidaigekidayo', publisher: 'Technos', region: 'Famicom', file: 'NES-Gamemusic/Famicom/Technos/Kunio_no_Jidaigekidayo.nsf' },
    { title: 'Nekketsu Hockey', publisher: 'Technos', region: 'Famicom', file: 'NES-Gamemusic/Famicom/Technos/Nekketsu_Hockey.nsf' },
    { title: 'Algos no Senshi', publisher: 'Tecmo', region: 'Famicom', file: 'NES-Gamemusic/Famicom/Tecmo/Algos_no_Senshi.nsf' },
    { title: 'Captain Tsubasa Vol2', publisher: 'Tecmo', region: 'Famicom', file: 'NES-Gamemusic/Famicom/Tecmo/Captain_Tsubasa_Vol2.nsf' },
    { title: 'Kyattou Ninden Teyande', publisher: 'Tecmo', region: 'Famicom', file: 'NES-Gamemusic/Famicom/Tecmo/Kyattou_Ninden_Teyande.nsf' },
    { title: 'Radia Senki', publisher: 'Tecmo', region: 'Famicom', file: 'NES-Gamemusic/Famicom/Tecmo/Radia_Senki.nsf' },
    { title: 'Super Star Force', publisher: 'Tecmo', region: 'Famicom', file: 'NES-Gamemusic/Famicom/Tecmo/Super_Star_Force.nsf' },
    { title: 'Tecmo World Cup Soccer', publisher: 'Tecmo', region: 'Famicom', file: 'NES-Gamemusic/Famicom/Tecmo/Tecmo_World_Cup_Soccer.nsf' },
    { title: 'Shikinjou', publisher: 'Toei Animation', region: 'Famicom', file: 'NES-Gamemusic/Famicom/Toei_Animation/Shikinjou.nsf' },
    { title: 'Nadia Secret of Blue Water', publisher: 'Toho', region: 'Famicom', file: 'NES-Gamemusic/Famicom/Toho/Nadia_Secret_of_Blue_Water.nsf' },
    { title: 'Labyrinth', publisher: 'Tokuma Shoten', region: 'Famicom', file: 'NES-Gamemusic/Famicom/Tokuma_Shoten/Labyrinth.nsf' },
    { title: 'Romancia', publisher: 'Tokyo Shoseki', region: 'Famicom', file: 'NES-Gamemusic/Famicom/Tokyo_Shoseki/Romancia.nsf' },
    { title: 'America Oudan Ultra Quiz', publisher: 'Tomy', region: 'Famicom', file: 'NES-Gamemusic/Famicom/Tomy/America_Oudan_Ultra_Quiz.nsf' },
    { title: 'Daiva', publisher: 'Toshiba EMI', region: 'Famicom', file: 'NES-Gamemusic/Famicom/Toshiba_EMI/Daiva.nsf' },
    { title: 'Idol Hakkenden', publisher: 'Towa Chiki', region: 'Famicom', file: 'NES-Gamemusic/Famicom/Towa_Chiki/Idol_Hakkenden.nsf' },
    { title: 'Ninja kun Ashura no Sho', publisher: 'UPL', region: 'Famicom', file: 'NES-Gamemusic/Famicom/UPL/Ninja_kun_Ashura_no_Sho.nsf' },
    { title: 'Batsu and Terry', publisher: 'Use', region: 'Famicom', file: 'NES-Gamemusic/Famicom/Use/Batsu_and_Terry.nsf' },
    { title: 'Parallel World', publisher: 'Varie', region: 'Famicom', file: 'NES-Gamemusic/Famicom/Varie/Parallel_World.nsf' },
    { title: 'Venus Senki', publisher: 'Varie', region: 'Famicom', file: 'NES-Gamemusic/Famicom/Varie/Venus_Senki.nsf' },
    { title: 'Ys III', publisher: 'Victor', region: 'Famicom', file: 'NES-Gamemusic/Famicom/Victor/Ys_III.nsf' },
    { title: 'Ys II', publisher: 'Victor', region: 'Famicom', file: 'NES-Gamemusic/Famicom/Victor/Ys_II.nsf' },
    { title: 'Ys', publisher: 'Victor', region: 'Famicom', file: 'NES-Gamemusic/Famicom/Victor/Ys.nsf' },
    { title: 'Gorilla Man', publisher: 'Yonezawa', region: 'Famicom', file: 'NES-Gamemusic/Famicom/Yonezawa/Gorilla_Man.nsf' },
    { title: 'SD Gundam Gachapon Senshi 4', publisher: 'Yutaka', region: 'Famicom', file: 'NES-Gamemusic/Famicom/Yutaka/SD_Gundam_Gachapon_Senshi_4.nsf' },
    { title: 'Ushio to Tora', publisher: 'Yutaka', region: 'Famicom', file: 'NES-Gamemusic/Famicom/Yutaka/Ushio_to_Tora.nsf' },
    { title: 'A Boy and His Blob', publisher: 'Absolute Entertainment', region: 'Nintendo', file: 'NES-Gamemusic/Nintendo/Absolute_Entertainment/A_Boy_and_His_Blob.nsf' },
    { title: 'Double Dragon 2', publisher: 'Acclaim', region: 'Nintendo', file: 'NES-Gamemusic/Nintendo/Acclaim/Double_Dragon_2.nsf' },
    { title: 'Double Dragon 3', publisher: 'Acclaim', region: 'Nintendo', file: 'NES-Gamemusic/Nintendo/Acclaim/Double_Dragon_3.nsf' },
    { title: 'Ferrari Grand Prix Challenge', publisher: 'Acclaim', region: 'Nintendo', file: 'NES-Gamemusic/Nintendo/Acclaim/Ferrari_Grand_Prix_Challenge.nsf' },
    { title: 'Rambo', publisher: 'Acclaim', region: 'Nintendo', file: 'NES-Gamemusic/Nintendo/Acclaim/Rambo.nsf' },
    { title: 'Tiger Heli', publisher: 'Acclaim', region: 'Nintendo', file: 'NES-Gamemusic/Nintendo/Acclaim/Tiger_Heli.nsf' },
    { title: 'Wizards and Warriors 1', publisher: 'Acclaim', region: 'Nintendo', file: 'NES-Gamemusic/Nintendo/Acclaim/Wizards_and_Warriors_1.nsf' },
    { title: 'Wizards and Warriors 2', publisher: 'Acclaim', region: 'Nintendo', file: 'NES-Gamemusic/Nintendo/Acclaim/Wizards_and_Warriors_2.nsf' },
    { title: 'Wizards and Warriors 3', publisher: 'Acclaim', region: 'Nintendo', file: 'NES-Gamemusic/Nintendo/Acclaim/Wizards_and_Warriors_3.nsf' },
    { title: 'WWF WrestleMania', publisher: 'Acclaim', region: 'Nintendo', file: 'NES-Gamemusic/Nintendo/Acclaim/WWF_WrestleMania.nsf' },
    { title: 'WWF Wrestling Challenge', publisher: 'Acclaim', region: 'Nintendo', file: 'NES-Gamemusic/Nintendo/Acclaim/WWF_Wrestling_Challenge.nsf' },
    { title: 'Die Hard', publisher: 'Activision', region: 'Nintendo', file: 'NES-Gamemusic/Nintendo/Activision/Die_Hard.nsf' },
    { title: 'Predator', publisher: 'Activision', region: 'Nintendo', file: 'NES-Gamemusic/Nintendo/Activision/Predator.nsf' },
    { title: 'Vice Project Doom', publisher: 'American Sammy', region: 'Nintendo', file: 'NES-Gamemusic/Nintendo/American_Sammy/Vice_Project_Doom.nsf' },
    { title: 'Treasure Master', publisher: 'American Softworks', region: 'Nintendo', file: 'NES-Gamemusic/Nintendo/American_Softworks/Treasure_Master.nsf' },
    { title: 'Gun Nac', publisher: 'Ascii', region: 'Nintendo', file: 'NES-Gamemusic/Nintendo/Ascii/Gun_Nac.nsf' },
    { title: 'Wizardry 1', publisher: 'Ascii', region: 'Nintendo', file: 'NES-Gamemusic/Nintendo/Ascii/Wizardry_1.nsf' },
    { title: 'Wizardry 2', publisher: 'Ascii', region: 'Nintendo', file: 'NES-Gamemusic/Nintendo/Ascii/Wizardry_2.nsf' },
    { title: 'Rockin Kats', publisher: 'Atlus', region: 'Nintendo', file: 'NES-Gamemusic/Nintendo/Atlus/Rockin_Kats.nsf' },
    { title: 'Wacky Races', publisher: 'Atlus', region: 'Nintendo', file: 'NES-Gamemusic/Nintendo/Atlus/Wacky_Races.nsf' },
    { title: 'Dr Jekyll and Mr Hyde', publisher: 'Bandai', region: 'Nintendo', file: 'NES-Gamemusic/Nintendo/Bandai/Dr_Jekyll_and_Mr_Hyde.nsf' },
    { title: 'MUSCLE', publisher: 'Bandai', region: 'Nintendo', file: 'NES-Gamemusic/Nintendo/Bandai/MUSCLE.nsf' },
    { title: 'Toxic Crusaders', publisher: 'Bandai', region: 'Nintendo', file: 'NES-Gamemusic/Nintendo/Bandai/Toxic_Crusaders.nsf' },
    { title: 'Guardian Legend', publisher: 'Broderbund', region: 'Nintendo', file: 'NES-Gamemusic/Nintendo/Broderbund/Guardian_Legend.nsf' },
    { title: 'Legacy of the Wizard', publisher: 'Broderbund', region: 'Nintendo', file: 'NES-Gamemusic/Nintendo/Broderbund/Legacy_of_the_Wizard.nsf' },
    { title: 'Raid on Bungeling Bay', publisher: 'Broderbund', region: 'Nintendo', file: 'NES-Gamemusic/Nintendo/Broderbund/Raid_on_Bungeling_Bay.nsf' },
    { title: 'Spelunker', publisher: 'Broderbund', region: 'Nintendo', file: 'NES-Gamemusic/Nintendo/Broderbund/Spelunker.nsf' },
    { title: 'Bee 52', publisher: 'Camerica', region: 'Nintendo', file: 'NES-Gamemusic/Nintendo/Camerica/Bee_52.nsf' },
    { title: 'Bignose Freaks Out', publisher: 'Camerica', region: 'Nintendo', file: 'NES-Gamemusic/Nintendo/Camerica/Bignose_Freaks_Out.nsf' },
    { title: 'Bignose the Caveman', publisher: 'Camerica', region: 'Nintendo', file: 'NES-Gamemusic/Nintendo/Camerica/Bignose_the_Caveman.nsf' },
    { title: 'Dizzy the Adventurer', publisher: 'Camerica', region: 'Nintendo', file: 'NES-Gamemusic/Nintendo/Camerica/Dizzy_the_Adventurer.nsf' },
    { title: 'Fantastic Adventures of Dizzy', publisher: 'Camerica', region: 'Nintendo', file: 'NES-Gamemusic/Nintendo/Camerica/Fantastic_Adventures_of_Dizzy.nsf' },
    { title: 'Firehawk', publisher: 'Camerica', region: 'Nintendo', file: 'NES-Gamemusic/Nintendo/Camerica/Firehawk.nsf' },
    { title: 'Linus Spaceheads Cosmic Crusade', publisher: 'Camerica', region: 'Nintendo', file: 'NES-Gamemusic/Nintendo/Camerica/Linus_Spaceheads_Cosmic_Crusade.nsf' },
    { title: 'Micro Machines', publisher: 'Camerica', region: 'Nintendo', file: 'NES-Gamemusic/Nintendo/Camerica/Micro_Machines.nsf' },
    { title: 'Mig 29 Soviet Fighter', publisher: 'Camerica', region: 'Nintendo', file: 'NES-Gamemusic/Nintendo/Camerica/Mig_29_Soviet_Fighter.nsf' },
    { title: 'Quattro Baseball Pros', publisher: 'Camerica', region: 'Nintendo', file: 'NES-Gamemusic/Nintendo/Camerica/Quattro_Baseball_Pros.nsf' },
    { title: 'Quattro BMX Simulator', publisher: 'Camerica', region: 'Nintendo', file: 'NES-Gamemusic/Nintendo/Camerica/Quattro_BMX_Simulator.nsf' },
    { title: 'Quattro Boomerang Kid', publisher: 'Camerica', region: 'Nintendo', file: 'NES-Gamemusic/Nintendo/Camerica/Quattro_Boomerang_Kid.nsf' },
    { title: 'Quattro CJs Elephant Antics', publisher: 'Camerica', region: 'Nintendo', file: 'NES-Gamemusic/Nintendo/Camerica/Quattro_CJs_Elephant_Antics.nsf' },
    { title: 'Quattro F15 Renegade', publisher: 'Camerica', region: 'Nintendo', file: 'NES-Gamemusic/Nintendo/Camerica/Quattro_F15_Renegade.nsf' },
    { title: 'Quattro Go Dizzy Go', publisher: 'Camerica', region: 'Nintendo', file: 'NES-Gamemusic/Nintendo/Camerica/Quattro_Go_Dizzy_Go.nsf' },
    { title: 'Quattro Linus Spacehead', publisher: 'Camerica', region: 'Nintendo', file: 'NES-Gamemusic/Nintendo/Camerica/Quattro_Linus_Spacehead.nsf' },
    { title: 'Quattro Pro Tennis', publisher: 'Camerica', region: 'Nintendo', file: 'NES-Gamemusic/Nintendo/Camerica/Quattro_Pro_Tennis.nsf' },
    { title: 'Quattro Soccer Simulator', publisher: 'Camerica', region: 'Nintendo', file: 'NES-Gamemusic/Nintendo/Camerica/Quattro_Soccer_Simulator.nsf' },
    { title: 'Quattro Stunt Buggies', publisher: 'Camerica', region: 'Nintendo', file: 'NES-Gamemusic/Nintendo/Camerica/Quattro_Stunt_Buggies.nsf' },
    { title: 'Quattro Super Robin Hood', publisher: 'Camerica', region: 'Nintendo', file: 'NES-Gamemusic/Nintendo/Camerica/Quattro_Super_Robin_Hood.nsf' },
    { title: 'Quattro Treasure Island Dizzy', publisher: 'Camerica', region: 'Nintendo', file: 'NES-Gamemusic/Nintendo/Camerica/Quattro_Treasure_Island_Dizzy.nsf' },
    { title: 'Stunt Kids', publisher: 'Camerica', region: 'Nintendo', file: 'NES-Gamemusic/Nintendo/Camerica/Stunt_Kids.nsf' },
    { title: 'Ultimate Stuntman', publisher: 'Camerica', region: 'Nintendo', file: 'NES-Gamemusic/Nintendo/Camerica/Ultimate_Stuntman.nsf' },
    { title: '1943', publisher: 'Capcom', region: 'Nintendo', file: 'NES-Gamemusic/Nintendo/Capcom/1943.nsf' },
    { title: 'Adventures in the Magic Kingdom', publisher: 'Capcom', region: 'Nintendo', file: 'NES-Gamemusic/Nintendo/Capcom/Adventures_in_the_Magic_Kingdom.nsf' },
    { title: 'Bionic Commando', publisher: 'Capcom', region: 'Nintendo', file: 'NES-Gamemusic/Nintendo/Capcom/Bionic_Commando.nsf' },
    { title: 'Chip n Dale Rescue Rangers 2', publisher: 'Capcom', region: 'Nintendo', file: 'NES-Gamemusic/Nintendo/Capcom/Chip_n_Dale_Rescue_Rangers_2.nsf' },
    { title: 'Chip n Dale Rescue Rangers', publisher: 'Capcom', region: 'Nintendo', file: 'NES-Gamemusic/Nintendo/Capcom/Chip_n_Dale_Rescue_Rangers.nsf' },
    { title: 'Code Name Viper', publisher: 'Capcom', region: 'Nintendo', file: 'NES-Gamemusic/Nintendo/Capcom/Code_Name_Viper.nsf' },
    { title: 'Commando', publisher: 'Capcom', region: 'Nintendo', file: 'NES-Gamemusic/Nintendo/Capcom/Commando.nsf' },
    { title: 'Darkwing Duck', publisher: 'Capcom', region: 'Nintendo', file: 'NES-Gamemusic/Nintendo/Capcom/Darkwing_Duck.nsf' },
    { title: 'Destiny of an Emperor', publisher: 'Capcom', region: 'Nintendo', file: 'NES-Gamemusic/Nintendo/Capcom/Destiny_of_an_Emperor.nsf' },
    { title: 'Duck Tales', publisher: 'Capcom', region: 'Nintendo', file: 'NES-Gamemusic/Nintendo/Capcom/Duck_Tales.nsf' },
    { title: 'Gargoyles Quest 2', publisher: 'Capcom', region: 'Nintendo', file: 'NES-Gamemusic/Nintendo/Capcom/Gargoyles_Quest_2.nsf' },
    { title: 'Ghosts and Goblins', publisher: 'Capcom', region: 'Nintendo', file: 'NES-Gamemusic/Nintendo/Capcom/Ghosts_and_Goblins.nsf' },
    { title: 'Gun Smoke', publisher: 'Capcom', region: 'Nintendo', file: 'NES-Gamemusic/Nintendo/Capcom/Gun_Smoke.nsf' },
    { title: 'Legendary Wings', publisher: 'Capcom', region: 'Nintendo', file: 'NES-Gamemusic/Nintendo/Capcom/Legendary_Wings.nsf' },
    { title: 'Little Mermaid', publisher: 'Capcom', region: 'Nintendo', file: 'NES-Gamemusic/Nintendo/Capcom/Little_Mermaid.nsf' },
    { title: 'Little Nemo the Dream Master', publisher: 'Capcom', region: 'Nintendo', file: 'NES-Gamemusic/Nintendo/Capcom/Little_Nemo_the_Dream_Master.nsf' },
    { title: 'Mega Man 2', publisher: 'Capcom', region: 'Nintendo', file: 'NES-Gamemusic/Nintendo/Capcom/Mega_Man_2.nsf' },
    { title: 'Mega Man 3', publisher: 'Capcom', region: 'Nintendo', file: 'NES-Gamemusic/Nintendo/Capcom/Mega_Man_3.nsf' },
    { title: 'Mega Man 4', publisher: 'Capcom', region: 'Nintendo', file: 'NES-Gamemusic/Nintendo/Capcom/Mega_Man_4.nsf' },
    { title: 'Mega Man 5', publisher: 'Capcom', region: 'Nintendo', file: 'NES-Gamemusic/Nintendo/Capcom/Mega_Man_5.nsf' },
    { title: 'Mega Man 6', publisher: 'Capcom', region: 'Nintendo', file: 'NES-Gamemusic/Nintendo/Capcom/Mega_Man_6.nsf' },
    { title: 'Mega Man', publisher: 'Capcom', region: 'Nintendo', file: 'NES-Gamemusic/Nintendo/Capcom/Mega_Man.nsf' },
    { title: 'Mighty Final Fight', publisher: 'Capcom', region: 'Nintendo', file: 'NES-Gamemusic/Nintendo/Capcom/Mighty_Final_Fight.nsf' },
    { title: 'Section Z', publisher: 'Capcom', region: 'Nintendo', file: 'NES-Gamemusic/Nintendo/Capcom/Section_Z.nsf' },
    { title: 'Street Fighter 2020', publisher: 'Capcom', region: 'Nintendo', file: 'NES-Gamemusic/Nintendo/Capcom/Street_Fighter_2020.nsf' },
    { title: 'Strider', publisher: 'Capcom', region: 'Nintendo', file: 'NES-Gamemusic/Nintendo/Capcom/Strider.nsf' },
    { title: 'Trojan', publisher: 'Capcom', region: 'Nintendo', file: 'NES-Gamemusic/Nintendo/Capcom/Trojan.nsf' },
    { title: 'Willow', publisher: 'Capcom', region: 'Nintendo', file: 'NES-Gamemusic/Nintendo/Capcom/Willow.nsf' },
    { title: 'Burgertime', publisher: 'Data East', region: 'Nintendo', file: 'NES-Gamemusic/Nintendo/Data_East/Burgertime.nsf' },
    { title: 'Captain America', publisher: 'Data East', region: 'Nintendo', file: 'NES-Gamemusic/Nintendo/Data_East/Captain_America.nsf' },
    { title: 'Tag Team Wrestling', publisher: 'Data East', region: 'Nintendo', file: 'NES-Gamemusic/Nintendo/Data_East/Tag_Team_Wrestling.nsf' },
    { title: 'Werewolf The Last Warrior', publisher: 'Data East', region: 'Nintendo', file: 'NES-Gamemusic/Nintendo/Data_East/Werewolf_The_Last_Warrior.nsf' },
    { title: 'Immortal', publisher: 'Electronic Arts', region: 'Nintendo', file: 'NES-Gamemusic/Nintendo/Electronic_Arts/Immortal.nsf' },
    { title: 'Skate Or Die 2', publisher: 'Electronic Arts', region: 'Nintendo', file: 'NES-Gamemusic/Nintendo/Electronic_Arts/Skate_Or_Die_2.nsf' },
    { title: 'Dragon Warrior 2', publisher: 'Enix', region: 'Nintendo', file: 'NES-Gamemusic/Nintendo/Enix/Dragon_Warrior_2.nsf' },
    { title: 'Dragon Warrior 3', publisher: 'Enix', region: 'Nintendo', file: 'NES-Gamemusic/Nintendo/Enix/Dragon_Warrior_3.nsf' },
    { title: 'Dragon Warrior 4', publisher: 'Enix', region: 'Nintendo', file: 'NES-Gamemusic/Nintendo/Enix/Dragon_Warrior_4.nsf' },
    { title: 'Hydlide', publisher: 'FCI', region: 'Nintendo', file: 'NES-Gamemusic/Nintendo/FCI/Hydlide.nsf' },
    { title: 'Magmax', publisher: 'FCI', region: 'Nintendo', file: 'NES-Gamemusic/Nintendo/FCI/Magmax.nsf' },
    { title: 'Terra Cresta', publisher: 'FCI', region: 'Nintendo', file: 'NES-Gamemusic/Nintendo/FCI/Terra_Cresta.nsf' },
    { title: 'Ultima Exodus', publisher: 'FCI', region: 'Nintendo', file: 'NES-Gamemusic/Nintendo/FCI/Ultima_Exodus.nsf' },
    { title: 'Zanac', publisher: 'FCI', region: 'Nintendo', file: 'NES-Gamemusic/Nintendo/FCI/Zanac.nsf' },
    { title: 'Nigel Mansells World Challenge', publisher: 'Gametek', region: 'Nintendo', file: 'NES-Gamemusic/Nintendo/Gametek/Nigel_Mansells_World_Challenge.nsf' },
    { title: 'Adventures of Lolo 2', publisher: 'HAL', region: 'Nintendo', file: 'NES-Gamemusic/Nintendo/HAL/Adventures_of_Lolo_2.nsf' },
    { title: 'Adventures of Lolo 3', publisher: 'HAL', region: 'Nintendo', file: 'NES-Gamemusic/Nintendo/HAL/Adventures_of_Lolo_3.nsf' },
    { title: 'Adventures of Lolo', publisher: 'HAL', region: 'Nintendo', file: 'NES-Gamemusic/Nintendo/HAL/Adventures_of_Lolo.nsf' },
    { title: 'Air Fortress', publisher: 'HAL', region: 'Nintendo', file: 'NES-Gamemusic/Nintendo/HAL/Air_Fortress.nsf' },
    { title: 'Kabuki Quantum Fighter', publisher: 'HAL', region: 'Nintendo', file: 'NES-Gamemusic/Nintendo/HAL/Kabuki_Quantum_Fighter.nsf' },
    { title: 'Barbie', publisher: 'High Tech Expressions', region: 'Nintendo', file: 'NES-Gamemusic/Nintendo/High_Tech_Expressions/Barbie.nsf' },
    { title: 'Tom and Jerry', publisher: 'High Tech Expressions', region: 'Nintendo', file: 'NES-Gamemusic/Nintendo/High_Tech_Expressions/Tom_and_Jerry.nsf' },
    { title: 'Adventure Island', publisher: 'Hudson Soft', region: 'Nintendo', file: 'NES-Gamemusic/Nintendo/Hudson_Soft/Adventure_Island.nsf' },
    { title: 'Adventures of Dino-Riki', publisher: 'Hudson Soft', region: 'Nintendo', file: 'NES-Gamemusic/Nintendo/Hudson_Soft/Adventures of Dino-Riki.nsf' },
    { title: 'Bomberman 2', publisher: 'Hudson Soft', region: 'Nintendo', file: 'NES-Gamemusic/Nintendo/Hudson_Soft/Bomberman_2.nsf' },
    { title: 'Bomberman', publisher: 'Hudson Soft', region: 'Nintendo', file: 'NES-Gamemusic/Nintendo/Hudson_Soft/Bomberman.nsf' },
    { title: 'Bonks Adventure', publisher: 'Hudson Soft', region: 'Nintendo', file: 'NES-Gamemusic/Nintendo/Hudson_Soft/Bonks_Adventure.nsf' },
    { title: 'Milons Secret Castle', publisher: 'Hudson Soft', region: 'Nintendo', file: 'NES-Gamemusic/Nintendo/Hudson_Soft/Milons_Secret_Castle.nsf' },
    { title: 'Princess Tomato Salad Kingdom', publisher: 'Hudson Soft', region: 'Nintendo', file: 'NES-Gamemusic/Nintendo/Hudson_Soft/Princess_Tomato_Salad_Kingdom.nsf' },
    { title: 'Robowarrior', publisher: 'Hudson Soft', region: 'Nintendo', file: 'NES-Gamemusic/Nintendo/Hudson_Soft/Robowarrior.nsf' },
    { title: 'Star Force NES', publisher: 'Hudson Soft', region: 'Nintendo', file: 'NES-Gamemusic/Nintendo/Hudson_Soft/Star_Force_NES.nsf' },
    { title: 'Starship Hector', publisher: 'Hudson Soft', region: 'Nintendo', file: 'NES-Gamemusic/Nintendo/Hudson_Soft/Starship_Hector.nsf' },
    { title: 'Xexyz', publisher: 'Hudson Soft', region: 'Nintendo', file: 'NES-Gamemusic/Nintendo/Hudson_Soft/Xexyz.nsf' },
    { title: 'Bram Stokers Dracula', publisher: 'Imagesoft', region: 'Nintendo', file: 'NES-Gamemusic/Nintendo/Imagesoft/Bram_Stokers_Dracula.nsf' },
    { title: 'Dragons Lair', publisher: 'Imagesoft', region: 'Nintendo', file: 'NES-Gamemusic/Nintendo/Imagesoft/Dragons_Lair.nsf' },
    { title: 'Solstice', publisher: 'Imagesoft', region: 'Nintendo', file: 'NES-Gamemusic/Nintendo/Imagesoft/Solstice.nsf' },
    { title: 'Tombs and Treasures', publisher: 'Infocom', region: 'Nintendo', file: 'NES-Gamemusic/Nintendo/Infocom/Tombs_and_Treasures.nsf' },
    { title: 'Asterix', publisher: 'Infogrames', region: 'Nintendo', file: 'NES-Gamemusic/Nintendo/Infogrames/Asterix.nsf' },
    { title: 'Smurfs', publisher: 'Infogrames', region: 'Nintendo', file: 'NES-Gamemusic/Nintendo/Infogrames/Smurfs.nsf' },
    { title: 'City Connection', publisher: 'Jaleco', region: 'Nintendo', file: 'NES-Gamemusic/Nintendo/Jaleco/City_Connection.nsf' },
    { title: 'Goal Two', publisher: 'Jaleco', region: 'Nintendo', file: 'NES-Gamemusic/Nintendo/Jaleco/Goal_Two.nsf' },
    { title: 'Maniac Mansion', publisher: 'Jaleco', region: 'Nintendo', file: 'NES-Gamemusic/Nintendo/Jaleco/Maniac_Mansion.nsf' },
    { title: 'Shatterhand', publisher: 'Jaleco', region: 'Nintendo', file: 'NES-Gamemusic/Nintendo/Jaleco/Shatterhand.nsf' },
    { title: 'Totally Rad', publisher: 'Jaleco', region: 'Nintendo', file: 'NES-Gamemusic/Nintendo/Jaleco/Totally_Rad.nsf' },
    { title: 'Deja Vu', publisher: 'Kemco Seika', region: 'Nintendo', file: 'NES-Gamemusic/Nintendo/Kemco_Seika/Deja_Vu.nsf' },
    { title: 'Rescue the Embassy Mission', publisher: 'Kemco Seika', region: 'Nintendo', file: 'NES-Gamemusic/Nintendo/Kemco_Seika/Rescue_the_Embassy_Mission.nsf' },
    { title: 'Shadowgate', publisher: 'Kemco Seika', region: 'Nintendo', file: 'NES-Gamemusic/Nintendo/Kemco_Seika/Shadowgate.nsf' },
    { title: 'Uncharted Waters', publisher: 'Koei', region: 'Nintendo', file: 'NES-Gamemusic/Nintendo/Koei/Uncharted_Waters.nsf' },
    { title: 'Adventures of Bayou Billy', publisher: 'Konami Ultra', region: 'Nintendo', file: 'NES-Gamemusic/Nintendo/Konami_Ultra/Adventures_of_Bayou_Billy.nsf' },
    { title: 'Batman Returns', publisher: 'Konami Ultra', region: 'Nintendo', file: 'NES-Gamemusic/Nintendo/Konami_Ultra/Batman_Returns.nsf' },
    { title: 'Bucky o Hare', publisher: 'Konami Ultra', region: 'Nintendo', file: 'NES-Gamemusic/Nintendo/Konami_Ultra/Bucky_o_Hare.nsf' },
    { title: 'Castlevania 2', publisher: 'Konami Ultra', region: 'Nintendo', file: 'NES-Gamemusic/Nintendo/Konami_Ultra/Castlevania_2.nsf' },
    { title: 'Castlevania 3', publisher: 'Konami Ultra', region: 'Nintendo', file: 'NES-Gamemusic/Nintendo/Konami_Ultra/Castlevania_3.nsf' },
    { title: 'Castlevania', publisher: 'Konami Ultra', region: 'Nintendo', file: 'NES-Gamemusic/Nintendo/Konami_Ultra/Castlevania.nsf' },
    { title: 'Contra', publisher: 'Konami Ultra', region: 'Nintendo', file: 'NES-Gamemusic/Nintendo/Konami_Ultra/Contra.nsf' },
    { title: 'Goonies 2', publisher: 'Konami Ultra', region: 'Nintendo', file: 'NES-Gamemusic/Nintendo/Konami_Ultra/Goonies_2.nsf' },
    { title: 'Gradius', publisher: 'Konami Ultra', region: 'Nintendo', file: 'NES-Gamemusic/Nintendo/Konami_Ultra/Gradius.nsf' },
    { title: 'Gyruss', publisher: 'Konami Ultra', region: 'Nintendo', file: 'NES-Gamemusic/Nintendo/Konami_Ultra/Gyruss.nsf' },
    { title: 'Jackal', publisher: 'Konami Ultra', region: 'Nintendo', file: 'NES-Gamemusic/Nintendo/Konami_Ultra/Jackal (1988-09)(Konami).nsf' },
    { title: 'Life Force', publisher: 'Konami Ultra', region: 'Nintendo', file: 'NES-Gamemusic/Nintendo/Konami_Ultra/Life_Force.nsf' },
    { title: 'Lone Ranger', publisher: 'Konami Ultra', region: 'Nintendo', file: 'NES-Gamemusic/Nintendo/Konami_Ultra/Lone_Ranger.nsf' },
    { title: 'Metal Gear', publisher: 'Konami Ultra', region: 'Nintendo', file: 'NES-Gamemusic/Nintendo/Konami_Ultra/Metal_Gear.nsf' },
    { title: 'Mission Impossible', publisher: 'Konami Ultra', region: 'Nintendo', file: 'NES-Gamemusic/Nintendo/Konami_Ultra/Mission_Impossible.nsf' },
    { title: 'Monster In My Pocket', publisher: 'Konami Ultra', region: 'Nintendo', file: 'NES-Gamemusic/Nintendo/Konami_Ultra/Monster_In_My_Pocket.nsf' },
    { title: 'Parodius', publisher: 'Konami Ultra', region: 'Nintendo', file: 'NES-Gamemusic/Nintendo/Konami_Ultra/Parodius.nsf' },
    { title: 'Rush n Attack', publisher: 'Konami Ultra', region: 'Nintendo', file: 'NES-Gamemusic/Nintendo/Konami_Ultra/Rush_n_Attack.nsf' },
    { title: 'Snakes Revenge', publisher: 'Konami Ultra', region: 'Nintendo', file: 'NES-Gamemusic/Nintendo/Konami_Ultra/Snakes_Revenge.nsf' },
    { title: 'Stinger', publisher: 'Konami Ultra', region: 'Nintendo', file: 'NES-Gamemusic/Nintendo/Konami_Ultra/Stinger.nsf' },
    { title: 'Super C', publisher: 'Konami Ultra', region: 'Nintendo', file: 'NES-Gamemusic/Nintendo/Konami_Ultra/Super_C.nsf' },
    { title: 'Tiny Toon Adventures 2', publisher: 'Konami Ultra', region: 'Nintendo', file: 'NES-Gamemusic/Nintendo/Konami_Ultra/Tiny_Toon_Adventures_2.nsf' },
    { title: 'Tiny Toon Adventures', publisher: 'Konami Ultra', region: 'Nintendo', file: 'NES-Gamemusic/Nintendo/Konami_Ultra/Tiny_Toon_Adventures.nsf' },
    { title: 'T M N T 1', publisher: 'Konami Ultra', region: 'Nintendo', file: 'NES-Gamemusic/Nintendo/Konami_Ultra/T_M_N_T_1.nsf' },
    { title: 'T M N T 2', publisher: 'Konami Ultra', region: 'Nintendo', file: 'NES-Gamemusic/Nintendo/Konami_Ultra/T_M_N_T_2.nsf' },
    { title: 'T M N T 3', publisher: 'Konami Ultra', region: 'Nintendo', file: 'NES-Gamemusic/Nintendo/Konami_Ultra/T_M_N_T_3.nsf' },
    { title: 'Top Gun', publisher: 'Konami Ultra', region: 'Nintendo', file: 'NES-Gamemusic/Nintendo/Konami_Ultra/Top_Gun.nsf' },
    { title: 'Top Gun The Second Mission', publisher: 'Konami Ultra', region: 'Nintendo', file: 'NES-Gamemusic/Nintendo/Konami_Ultra/Top_Gun_The_Second_Mission.nsf' },
    { title: 'Track and Field 2', publisher: 'Konami Ultra', region: 'Nintendo', file: 'NES-Gamemusic/Nintendo/Konami_Ultra/Track_and_Field_2.nsf' },
    { title: 'Zen Intergalactic Ninja', publisher: 'Konami Ultra', region: 'Nintendo', file: 'NES-Gamemusic/Nintendo/Konami_Ultra/Zen_Intergalactic_Ninja.nsf' },
    { title: 'Alien 3', publisher: 'LJN', region: 'Nintendo', file: 'NES-Gamemusic/Nintendo/LJN/Alien_3.nsf' },
    { title: 'Friday the 13th', publisher: 'LJN', region: 'Nintendo', file: 'NES-Gamemusic/Nintendo/LJN/Friday_the_13th.nsf' },
    { title: 'Gotcha The Sport', publisher: 'LJN', region: 'Nintendo', file: 'NES-Gamemusic/Nintendo/LJN/Gotcha_The_Sport.nsf' },
    { title: 'Incredible Crash Dummies', publisher: 'LJN', region: 'Nintendo', file: 'NES-Gamemusic/Nintendo/LJN/Incredible_Crash_Dummies.nsf' },
    { title: 'Karate Kid', publisher: 'LJN', region: 'Nintendo', file: 'NES-Gamemusic/Nintendo/LJN/Karate_Kid.nsf' },
    { title: 'NFL Football', publisher: 'LJN', region: 'Nintendo', file: 'NES-Gamemusic/Nintendo/LJN/NFL_Football.nsf' },
    { title: 'Nightmare on Elm Street', publisher: 'LJN', region: 'Nintendo', file: 'NES-Gamemusic/Nintendo/LJN/Nightmare_on_Elm_Street.nsf' },
    { title: 'Pictionary', publisher: 'LJN', region: 'Nintendo', file: 'NES-Gamemusic/Nintendo/LJN/Pictionary.nsf' },
    { title: 'Spiderman', publisher: 'LJN', region: 'Nintendo', file: 'NES-Gamemusic/Nintendo/LJN/Spiderman.nsf' },
    { title: 'Terminator 2', publisher: 'LJN', region: 'Nintendo', file: 'NES-Gamemusic/Nintendo/LJN/Terminator_2.nsf' },
    { title: 'Wolverine', publisher: 'LJN', region: 'Nintendo', file: 'NES-Gamemusic/Nintendo/LJN/Wolverine.nsf' },
    { title: 'Zombie Nation', publisher: 'Meldac', region: 'Nintendo', file: 'NES-Gamemusic/Nintendo/Meldac/Zombie_Nation.nsf' },
    { title: 'Abadox', publisher: 'Milton Bradley', region: 'Nintendo', file: 'NES-Gamemusic/Nintendo/Milton_Bradley/Abadox.nsf' },
    { title: 'Alfred Chicken', publisher: 'Mindscape', region: 'Nintendo', file: 'NES-Gamemusic/Nintendo/Mindscape/Alfred_Chicken.nsf' },
    { title: 'SCAT', publisher: 'Natsume', region: 'Nintendo', file: 'NES-Gamemusic/Nintendo/Natsume/SCAT.nsf' },
    { title: 'Shadow of the Ninja', publisher: 'Natsume', region: 'Nintendo', file: 'NES-Gamemusic/Nintendo/Natsume/Shadow_of_the_Ninja.nsf' },
    { title: 'Castlequest', publisher: 'Nexoft', region: 'Nintendo', file: 'NES-Gamemusic/Nintendo/Nexoft/Castlequest.nsf' },
    { title: 'Balloon Fight', publisher: 'Nintendo', region: 'Nintendo', file: 'NES-Gamemusic/Nintendo/Nintendo/Balloon_Fight.nsf' },
    { title: 'Clu Clu Land', publisher: 'Nintendo', region: 'Nintendo', file: 'NES-Gamemusic/Nintendo/Nintendo/Clu_Clu_Land.nsf' },
    { title: 'Cobra Triangle', publisher: 'Nintendo', region: 'Nintendo', file: 'NES-Gamemusic/Nintendo/Nintendo/Cobra_Triangle.nsf' },
    { title: 'Donkey Kong 3', publisher: 'Nintendo', region: 'Nintendo', file: 'NES-Gamemusic/Nintendo/Nintendo/Donkey_Kong_3.nsf' },
    { title: 'Donkey Kong Jr', publisher: 'Nintendo', region: 'Nintendo', file: 'NES-Gamemusic/Nintendo/Nintendo/Donkey_Kong_Jr.nsf' },
    { title: 'Donkey Kong', publisher: 'Nintendo', region: 'Nintendo', file: 'NES-Gamemusic/Nintendo/Nintendo/Donkey_Kong.nsf' },
    { title: 'Dragon Warrior', publisher: 'Nintendo', region: 'Nintendo', file: 'NES-Gamemusic/Nintendo/Nintendo/Dragon_Warrior.nsf' },
    { title: 'Dr Mario', publisher: 'Nintendo', region: 'Nintendo', file: 'NES-Gamemusic/Nintendo/Nintendo/Dr_Mario.nsf' },
    { title: 'Earthbound', publisher: 'Nintendo', region: 'Nintendo', file: 'NES-Gamemusic/Nintendo/Nintendo/Earthbound.nsf' },
    { title: 'Excitebike', publisher: 'Nintendo', region: 'Nintendo', file: 'NES-Gamemusic/Nintendo/Nintendo/Excitebike.nsf' },
    { title: 'Faxanadu', publisher: 'Nintendo', region: 'Nintendo', file: 'NES-Gamemusic/Nintendo/Nintendo/Faxanadu.nsf' },
    { title: 'Final Fantasy', publisher: 'Nintendo', region: 'Nintendo', file: 'NES-Gamemusic/Nintendo/Nintendo/Final_Fantasy.nsf' },
    { title: 'Gumshoe', publisher: 'Nintendo', region: 'Nintendo', file: 'NES-Gamemusic/Nintendo/Nintendo/Gumshoe.nsf' },
    { title: 'Gyromite', publisher: 'Nintendo', region: 'Nintendo', file: 'NES-Gamemusic/Nintendo/Nintendo/Gyromite.nsf' },
    { title: 'Kid Icarus', publisher: 'Nintendo', region: 'Nintendo', file: 'NES-Gamemusic/Nintendo/Nintendo/Kid_Icarus.nsf' },
    { title: 'Kirbys Adventure', publisher: 'Nintendo', region: 'Nintendo', file: 'NES-Gamemusic/Nintendo/Nintendo/Kirbys_Adventure.nsf' },
    { title: 'Kung Fu', publisher: 'Nintendo', region: 'Nintendo', file: 'NES-Gamemusic/Nintendo/Nintendo/Kung_Fu.nsf' },
    { title: 'Legend of Zelda', publisher: 'Nintendo', region: 'Nintendo', file: 'NES-Gamemusic/Nintendo/Nintendo/Legend_of_Zelda.nsf' },
    { title: 'Mach Rider', publisher: 'Nintendo', region: 'Nintendo', file: 'NES-Gamemusic/Nintendo/Nintendo/Mach_Rider.nsf' },
    { title: 'Mario Brothers', publisher: 'Nintendo', region: 'Nintendo', file: 'NES-Gamemusic/Nintendo/Nintendo/Mario_Brothers.nsf' },
    { title: 'Metroid', publisher: 'Nintendo', region: 'Nintendo', file: 'NES-Gamemusic/Nintendo/Nintendo/Metroid.nsf' },
    { title: 'Nintendo World Cup', publisher: 'Nintendo', region: 'Nintendo', file: 'NES-Gamemusic/Nintendo/Nintendo/Nintendo_World_Cup.nsf' },
    { title: 'Popeye', publisher: 'Nintendo', region: 'Nintendo', file: 'NES-Gamemusic/Nintendo/Nintendo/Popeye.nsf' },
    { title: 'Rad Racer', publisher: 'Nintendo', region: 'Nintendo', file: 'NES-Gamemusic/Nintendo/Nintendo/Rad_Racer.nsf' },
    { title: 'Snake Rattle and Roll', publisher: 'Nintendo', region: 'Nintendo', file: 'NES-Gamemusic/Nintendo/Nintendo/Snake_Rattle_and_Roll.nsf' },
    { title: 'Soccer', publisher: 'Nintendo', region: 'Nintendo', file: 'NES-Gamemusic/Nintendo/Nintendo/Soccer.nsf' },
    { title: 'Stack up', publisher: 'Nintendo', region: 'Nintendo', file: 'NES-Gamemusic/Nintendo/Nintendo/Stack_up.nsf' },
    { title: 'Super Mario Bros 2', publisher: 'Nintendo', region: 'Nintendo', file: 'NES-Gamemusic/Nintendo/Nintendo/Super_Mario_Bros_2.nsf' },
    { title: 'Super Mario Bros 3', publisher: 'Nintendo', region: 'Nintendo', file: 'NES-Gamemusic/Nintendo/Nintendo/Super_Mario_Bros_3.nsf' },
    { title: 'Super Mario Bros', publisher: 'Nintendo', region: 'Nintendo', file: 'NES-Gamemusic/Nintendo/Nintendo/Super_Mario_Bros.nsf' },
    { title: 'Super Spike V Ball', publisher: 'Nintendo', region: 'Nintendo', file: 'NES-Gamemusic/Nintendo/Nintendo/Super_Spike_V_Ball.nsf' },
    { title: 'Urban Champion', publisher: 'Nintendo', region: 'Nintendo', file: 'NES-Gamemusic/Nintendo/Nintendo/Urban_Champion.nsf' },
    { title: 'Vs Balloon Fight', publisher: 'Nintendo', region: 'Nintendo', file: 'NES-Gamemusic/Nintendo/Nintendo/Vs_Balloon_Fight.nsf' },
    { title: 'Vs Clu Clu Land', publisher: 'Nintendo', region: 'Nintendo', file: 'NES-Gamemusic/Nintendo/Nintendo/Vs_Clu_Clu_Land.nsf' },
    { title: 'Vs Excitebike', publisher: 'Nintendo', region: 'Nintendo', file: 'NES-Gamemusic/Nintendo/Nintendo/Vs_Excitebike.nsf' },
    { title: 'Vs Wrecking Crew', publisher: 'Nintendo', region: 'Nintendo', file: 'NES-Gamemusic/Nintendo/Nintendo/Vs_Wrecking_Crew.nsf' },
    { title: 'Wrecking Crew', publisher: 'Nintendo', region: 'Nintendo', file: 'NES-Gamemusic/Nintendo/Nintendo/Wrecking_Crew.nsf' },
    { title: 'Zelda 2 Adventure of Link', publisher: 'Nintendo', region: 'Nintendo', file: 'NES-Gamemusic/Nintendo/Nintendo/Zelda_2_Adventure_of_Link.nsf' },
    { title: 'Isolated Warrior', publisher: 'NTVIC', region: 'Nintendo', file: 'NES-Gamemusic/Nintendo/NTVIC/Isolated_Warrior.nsf' },
    { title: 'Darkman', publisher: 'Ocean', region: 'Nintendo', file: 'NES-Gamemusic/Nintendo/Ocean/Darkman.nsf' },
    { title: 'Hook', publisher: 'Ocean', region: 'Nintendo', file: 'NES-Gamemusic/Nintendo/Ocean/Hook.nsf' },
    { title: 'Hudson Hawk', publisher: 'Ocean', region: 'Nintendo', file: 'NES-Gamemusic/Nintendo/Ocean/Hudson_Hawk.nsf' },
    { title: 'Jurassic Park', publisher: 'Ocean', region: 'Nintendo', file: 'NES-Gamemusic/Nintendo/Ocean/Jurassic_Park.nsf' },
    { title: 'Robocop 2', publisher: 'Ocean', region: 'Nintendo', file: 'NES-Gamemusic/Nintendo/Ocean/Robocop_2.nsf' },
    { title: 'Robocop 3', publisher: 'Ocean', region: 'Nintendo', file: 'NES-Gamemusic/Nintendo/Ocean/Robocop_3.nsf' },
    { title: 'Cowboy Kid', publisher: 'Romstar', region: 'Nintendo', file: 'NES-Gamemusic/Nintendo/Romstar/Cowboy_Kid.nsf' },
    { title: 'World Champ', publisher: 'Romstar', region: 'Nintendo', file: 'NES-Gamemusic/Nintendo/Romstar/World_Champ.nsf' },
    { title: 'Alloy Run Mix', publisher: 'Scene Demos', region: 'Nintendo', file: 'NES-Gamemusic/Nintendo/Scene_Demos/Alloy_Run_Mix.nsf' },
    { title: 'Comic Bakery', publisher: 'Scene Demos', region: 'Nintendo', file: 'NES-Gamemusic/Nintendo/Scene_Demos/Comic_Bakery.nsf' },
    { title: 'Dance of the Sugarplum Faries', publisher: 'Scene Demos', region: 'Nintendo', file: 'NES-Gamemusic/Nintendo/Scene_Demos/Dance_of_the_Sugarplum_Faries.nsf' },
    { title: 'Gianna', publisher: 'Scene Demos', region: 'Nintendo', file: 'NES-Gamemusic/Nintendo/Scene_Demos/Gianna.nsf' },
    { title: 'GoldRunner Music Demo', publisher: 'Scene Demos', region: 'Nintendo', file: 'NES-Gamemusic/Nintendo/Scene_Demos/GoldRunner_Music_Demo.nsf' },
    { title: 'Snow', publisher: 'Scene Demos', region: 'Nintendo', file: 'NES-Gamemusic/Nintendo/Scene_Demos/Snow.nsf' },
    { title: 'Solar Wars', publisher: 'Scene Demos', region: 'Nintendo', file: 'NES-Gamemusic/Nintendo/Scene_Demos/Solar_Wars.nsf' },
    { title: 'Crystalis', publisher: 'SNK', region: 'Nintendo', file: 'NES-Gamemusic/Nintendo/SNK/Crystalis.nsf' },
    { title: 'Guerilla War', publisher: 'SNK', region: 'Nintendo', file: 'NES-Gamemusic/Nintendo/SNK/Guerilla_War.nsf' },
    { title: 'P O W', publisher: 'SNK', region: 'Nintendo', file: 'NES-Gamemusic/Nintendo/SNK/P_O_W.nsf' },
    { title: 'Dragon Fighter', publisher: 'Sofel', region: 'Nintendo', file: 'NES-Gamemusic/Nintendo/Sofel/Dragon_Fighter.nsf' },
    { title: 'Kings Knight', publisher: 'Square', region: 'Nintendo', file: 'NES-Gamemusic/Nintendo/Square/Kings_Knight.nsf' },
    { title: 'Batman', publisher: 'Sunsoft', region: 'Nintendo', file: 'NES-Gamemusic/Nintendo/Sunsoft/Batman.nsf' },
    { title: 'Batman Return of The Joker', publisher: 'Sunsoft', region: 'Nintendo', file: 'NES-Gamemusic/Nintendo/Sunsoft/Batman_Return_of_The_Joker.nsf' },
    { title: 'Blaster Master', publisher: 'Sunsoft', region: 'Nintendo', file: 'NES-Gamemusic/Nintendo/Sunsoft/Blaster_Master.nsf' },
    { title: 'Festers Quest', publisher: 'Sunsoft', region: 'Nintendo', file: 'NES-Gamemusic/Nintendo/Sunsoft/Festers_Quest.nsf' },
    { title: 'Gremlins 2', publisher: 'Sunsoft', region: 'Nintendo', file: 'NES-Gamemusic/Nintendo/Sunsoft/Gremlins_2.nsf' },
    { title: 'Journey to Silius', publisher: 'Sunsoft', region: 'Nintendo', file: 'NES-Gamemusic/Nintendo/Sunsoft/Journey_to_Silius.nsf' },
    { title: 'Lemmings', publisher: 'Sunsoft', region: 'Nintendo', file: 'NES-Gamemusic/Nintendo/Sunsoft/Lemmings.nsf' },
    { title: 'Platoon', publisher: 'Sunsoft', region: 'Nintendo', file: 'NES-Gamemusic/Nintendo/Sunsoft/Platoon.nsf' },
    { title: 'Spy Hunter', publisher: 'Sunsoft', region: 'Nintendo', file: 'NES-Gamemusic/Nintendo/Sunsoft/Spy_Hunter.nsf' },
    { title: 'Super Spy Hunter', publisher: 'Sunsoft', region: 'Nintendo', file: 'NES-Gamemusic/Nintendo/Sunsoft/Super_Spy_Hunter.nsf' },
    { title: 'Bubble Bobble', publisher: 'Taito', region: 'Nintendo', file: 'NES-Gamemusic/Nintendo/Taito/Bubble_Bobble.nsf' },
    { title: 'Chase HQ', publisher: 'Taito', region: 'Nintendo', file: 'NES-Gamemusic/Nintendo/Taito/Chase_HQ.nsf' },
    { title: 'Dungeon Magic', publisher: 'Taito', region: 'Nintendo', file: 'NES-Gamemusic/Nintendo/Taito/Dungeon_Magic.nsf' },
    { title: 'Indiana Jones and the Last Crusade', publisher: 'Taito', region: 'Nintendo', file: 'NES-Gamemusic/Nintendo/Taito/Indiana_Jones_and_the_Last_Crusade.nsf' },
    { title: 'Jetsons', publisher: 'Taito', region: 'Nintendo', file: 'NES-Gamemusic/Nintendo/Taito/Jetsons.nsf' },
    { title: 'Kick Master', publisher: 'Taito', region: 'Nintendo', file: 'NES-Gamemusic/Nintendo/Taito/Kick_Master.nsf' },
    { title: 'Legend of Kage', publisher: 'Taito', region: 'Nintendo', file: 'NES-Gamemusic/Nintendo/Taito/Legend_of_Kage.nsf' },
    { title: 'Little Samson', publisher: 'Taito', region: 'Nintendo', file: 'NES-Gamemusic/Nintendo/Taito/Little_Samson.nsf' },
    { title: 'Panic Restaurant', publisher: 'Taito', region: 'Nintendo', file: 'NES-Gamemusic/Nintendo/Taito/Panic_Restaurant.nsf' },
    { title: 'Power Blade 2', publisher: 'Taito', region: 'Nintendo', file: 'NES-Gamemusic/Nintendo/Taito/Power_Blade_2.nsf' },
    { title: 'Power Blade', publisher: 'Taito', region: 'Nintendo', file: 'NES-Gamemusic/Nintendo/Taito/Power_Blade.nsf' },
    { title: 'Sky Shark', publisher: 'Taito', region: 'Nintendo', file: 'NES-Gamemusic/Nintendo/Taito/Sky_Shark.nsf' },
    { title: 'Target Renegade', publisher: 'Taito', region: 'Nintendo', file: 'NES-Gamemusic/Nintendo/Taito/Target_Renegade.nsf' },
    { title: '8 Eyes', publisher: 'Taxan', region: 'Nintendo', file: 'NES-Gamemusic/Nintendo/Taxan/8_Eyes.nsf' },
    { title: 'Burai Fighter', publisher: 'Taxan', region: 'Nintendo', file: 'NES-Gamemusic/Nintendo/Taxan/Burai_Fighter.nsf' },
    { title: 'Magician', publisher: 'Taxan', region: 'Nintendo', file: 'NES-Gamemusic/Nintendo/Taxan/Magician.nsf' },
    { title: 'Mappyland', publisher: 'Taxan', region: 'Nintendo', file: 'NES-Gamemusic/Nintendo/Taxan/Mappyland.nsf' },
    { title: 'Star Soldier', publisher: 'Taxan', region: 'Nintendo', file: 'NES-Gamemusic/Nintendo/Taxan/Star_Soldier.nsf' },
    { title: 'Crash n the Boys Street Challenge', publisher: 'Technos', region: 'Nintendo', file: 'NES-Gamemusic/Nintendo/Technos/Crash_n_the_Boys_Street_Challenge.nsf' },
    { title: 'River City Ransom', publisher: 'Technos', region: 'Nintendo', file: 'NES-Gamemusic/Nintendo/Technos/River_City_Ransom.nsf' },
    { title: 'Mighty Bombjack', publisher: 'Tecmo', region: 'Nintendo', file: 'NES-Gamemusic/Nintendo/Tecmo/Mighty_Bombjack.nsf' },
    { title: 'Ninja Gaiden 2', publisher: 'Tecmo', region: 'Nintendo', file: 'NES-Gamemusic/Nintendo/Tecmo/Ninja_Gaiden_2.nsf' },
    { title: 'Ninja Gaiden 3', publisher: 'Tecmo', region: 'Nintendo', file: 'NES-Gamemusic/Nintendo/Tecmo/Ninja_Gaiden_3.nsf' },
    { title: 'Ninja Gaiden', publisher: 'Tecmo', region: 'Nintendo', file: 'NES-Gamemusic/Nintendo/Tecmo/Ninja_Gaiden.nsf' },
    { title: 'Rygar', publisher: 'Tecmo', region: 'Nintendo', file: 'NES-Gamemusic/Nintendo/Tecmo/Rygar.nsf' },
    { title: 'Solomons Key', publisher: 'Tecmo', region: 'Nintendo', file: 'NES-Gamemusic/Nintendo/Tecmo/Solomons_Key.nsf' },
    { title: 'Tecmo Bowl', publisher: 'Tecmo', region: 'Nintendo', file: 'NES-Gamemusic/Nintendo/Tecmo/Tecmo_Bowl.nsf' },
    { title: 'Tecmo Cup Soccer Game', publisher: 'Tecmo', region: 'Nintendo', file: 'NES-Gamemusic/Nintendo/Tecmo/Tecmo_Cup_Soccer_Game.nsf' },
    { title: 'Tecmo World Wrestling', publisher: 'Tecmo', region: 'Nintendo', file: 'NES-Gamemusic/Nintendo/Tecmo/Tecmo_World_Wrestling.nsf' },
    { title: 'Fantasy Zone NES', publisher: 'Tengen', region: 'Nintendo', file: 'NES-Gamemusic/Nintendo/Tengen/Fantasy_Zone_NES.nsf' },
    { title: 'Klax', publisher: 'Tengen', region: 'Nintendo', file: 'NES-Gamemusic/Nintendo/Tengen/Klax.nsf' },
    { title: 'RBI Baseball', publisher: 'Tengen', region: 'Nintendo', file: 'NES-Gamemusic/Nintendo/Tengen/RBI_Baseball.nsf' },
    { title: 'Shinobi', publisher: 'Tengen', region: 'Nintendo', file: 'NES-Gamemusic/Nintendo/Tengen/Shinobi.nsf' },
    { title: 'Tetris Tengen', publisher: 'Tengen', region: 'Nintendo', file: 'NES-Gamemusic/Nintendo/Tengen/Tetris_Tengen.nsf' },
    { title: 'Attack of the Killer Tomatoes', publisher: 'THQ', region: 'Nintendo', file: 'NES-Gamemusic/Nintendo/THQ/Attack_of_the_Killer_Tomatoes.nsf' },
    { title: 'Battletoads and Double Dragon', publisher: 'Tradewest', region: 'Nintendo', file: 'NES-Gamemusic/Nintendo/Tradewest/Battletoads_and_Double_Dragon.nsf' },
    { title: 'Battletoads', publisher: 'Tradewest', region: 'Nintendo', file: 'NES-Gamemusic/Nintendo/Tradewest/Battletoads.nsf' },
    { title: 'Double Dragon', publisher: 'Tradewest', region: 'Nintendo', file: 'NES-Gamemusic/Nintendo/Tradewest/Double_Dragon.nsf' },
    { title: 'Magic Johnsons Fast Break', publisher: 'Tradewest', region: 'Nintendo', file: 'NES-Gamemusic/Nintendo/Tradewest/Magic_Johnsons_Fast_Break.nsf' },
    { title: 'Solar Jetman', publisher: 'Tradewest', region: 'Nintendo', file: 'NES-Gamemusic/Nintendo/Tradewest/Solar_Jetman.nsf' },
    { title: 'Bump N Jump', publisher: 'Vic Tokai', region: 'Nintendo', file: 'NES-Gamemusic/Nintendo/Vic_Tokai/Bump_N_Jump.nsf' },
    { title: 'Krion Conquest', publisher: 'Vic Tokai', region: 'Nintendo', file: 'NES-Gamemusic/Nintendo/Vic_Tokai/Krion_Conquest.nsf' },
    { title: 'Jungle Book', publisher: 'Virgin', region: 'Nintendo', file: 'NES-Gamemusic/Nintendo/Virgin/Jungle_Book.nsf' },
    { title: 'MC Kids', publisher: 'Virgin', region: 'Nintendo', file: 'NES-Gamemusic/Nintendo/Virgin/MC_Kids.nsf' },
    { title: 'Silver Surfer', publisher: 'Virgin', region: 'Nintendo', file: 'NES-Gamemusic/Nintendo/Virgin/Silver_Surfer.nsf' },
];
